<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="BK Advisors">
  <meta name="dcterms.date" content="2026-02-12">
  <title>Chapter 5: Situational Analysis</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-afce544662d4c774d79a6cccbbed54ef.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section data-background-color="#005CB9" class="quarto-title-block center">
  <h1 class="title">Chapter 5: Situational Analysis</h1>
  <p class="subtitle">Inference and Intervention | BK Advisors</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
BK Advisors 
</div>
</div>
</div>

  <p class="date">2026-02-12</p>
</section>
<section class="slide level2">
<h2>Learning Objectives</h2>
<p>After this chapter, you will be able to:</p>
<ul>
<li class="fragment">Compute <strong>marginal probabilities</strong> by summing out variables from joint distributions</li>
<li class="fragment"><strong>Update beliefs with evidence</strong> using Bayes’ rule and conditional probability</li>
<li class="fragment">Perform <strong>inference in serial, diverging, and converging structures</strong> and explain how information flows differently in each</li>
<li class="fragment">Apply the <strong>explaining away</strong> phenomenon in converging structures — the most counterintuitive result in causal reasoning</li>
<li class="fragment">Conduct a full <strong>district diagnosis</strong> using Bayesian inference on an MNH causal model</li>
</ul>
</section>
<section class="slide level2">
<h2>Chapter Overview</h2>
<div class="step-flow">
<div class="step-item" style="border-left: 4px solid #005CB9;">
Marginal<br>Probabilities
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #83BD00;">
Evidence &amp;<br>Updating
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #F8A623;">
Serial &amp;<br>Diverging
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #E24A3F;">
Converging &amp;<br>Explaining Away
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #3E9B6E;">
District<br>Diagnosis
</div>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>Core Insight:</strong> In Chapter 4 we learned to build quantitative models <em>forward</em> — specifying how causes produce effects. In Chapter 5 we run the model <strong>backwards</strong> — observing outcomes and inferring what caused them. This is the heart of situational analysis.</p>
</div>
</div>
</section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>The Manager’s Inference Problem</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Running the model backwards</span></p>
</section>
<section class="slide level2">
<h2>From Forward to Backward Reasoning</h2>
<div class="definition-box">
<p><strong>Situational Analysis:</strong> The process of observing outcomes and using a quantitative causal model to <em>infer</em> the most likely state of unobserved causes. We run the model “backwards” — from effects to causes.</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>Chapter 4 (Forward)</strong></p>
<p>Given causes, predict effects:</p>
<p>“<em>If</em> staffing is low and equipment unavailable, <em>what is the probability</em> of high NMR?”</p>
<p>Direction: Parents → Children</p>
</div>
</div>
<div class="col">
<div class="callout-box orange">
<p><strong>Chapter 5 (Backward)</strong></p>
<p>Given effects, infer causes:</p>
<p>“We <em>observe</em> high NMR in a district — <em>what does this tell us</em> about staffing and equipment?”</p>
<p>Direction: Children → Parents</p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">
<h2>The MNH Inference Model</h2>
<p>We use a simplified model throughout this chapter:</p>
<table style="width: 85%; margin: 0.5em auto; font-size: 0.5em;">
<tbody><tr>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node treatment rect">
Staffing<br>(S)
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow">↘</span>
</td>
<td>
</td>
<td style="text-align: center;">
<span class="dag-arrow">↙</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node treatment rect">
Equipment<br>(E)
</div>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node">
Workforce<br>Quality (Q)
</div>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td style="text-align: center;">
<span class="dag-arrow">↓</span>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node outcome">
Neonatal Mortality<br>Rate (NMR)
</div>
</td>
<td>
</td>
<td>
</td>
</tr>
</tbody></table>
<div class="fragment">
<p><strong>Prior probabilities (from Chapter 4):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>States</th>
<th>Prior</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Staffing (S)</strong></td>
<td>Adequate / Low</td>
<td>0.40 / 0.60</td>
</tr>
<tr class="even">
<td><strong>Equipment (E)</strong></td>
<td>Available / Unavailable</td>
<td>0.35 / 0.65</td>
</tr>
<tr class="odd">
<td><strong>Training (T)</strong></td>
<td>Completed / Not Completed</td>
<td>0.50 / 0.50</td>
</tr>
</tbody>
</table>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Marginal Probabilities</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">What is the overall probability of an outcome?</span></p>
</section>
<section class="slide level2">
<h2>What Is a Marginal Probability?</h2>
<div class="definition-box">
<p><strong>Marginal Probability:</strong> The probability of a variable computed by <strong>summing out</strong> (marginalizing over) all other variables in the joint distribution. It tells us the overall likelihood of an event, averaging across all possible parent combinations.</p>
</div>
<div class="fragment">
<div class="math-block">
<p><span class="math display">\[P(X) = \sum_{\text{all other variables}} P(X, Y_1, Y_2, \ldots, Y_n)\]</span></p>
</div>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>Intuition:</strong> “What is the overall probability that NMR is High in a randomly selected district?” We don’t know the district’s staffing or equipment — so we average over <em>all possible</em> staffing/equipment combinations, weighted by how likely each combination is.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Computing Marginal NMR</h2>
<p><strong>CPT for Quality given Staffing and Equipment:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Staffing</th>
<th>Equipment</th>
<th>P(Q=Good)</th>
<th>P(Q=Poor)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adequate</td>
<td>Available</td>
<td>0.90</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>Adequate</td>
<td>Unavailable</td>
<td>0.60</td>
<td>0.40</td>
</tr>
<tr class="odd">
<td>Low</td>
<td>Available</td>
<td>0.50</td>
<td>0.50</td>
</tr>
<tr class="even">
<td>Low</td>
<td>Unavailable</td>
<td>0.15</td>
<td>0.85</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>CPT for NMR given Quality:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Quality</th>
<th>P(NMR=Low)</th>
<th>P(NMR=High)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Good</td>
<td>0.85</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>Poor</td>
<td>0.30</td>
<td>0.70</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">
<h2>Marginal P(NMR=High): The Calculation</h2>
<p>We sum over all paths through the network:</p>
<div class="math-block">
<p><span class="math display">\[P(\text{NMR=High}) = \sum_{s,e,q} P(S=s) \cdot P(E=e) \cdot P(Q=q \mid S=s, E=e) \cdot P(\text{NMR=High} \mid Q=q)\]</span></p>
</div>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>S</th>
<th>E</th>
<th>P(S)</th>
<th>P(E)</th>
<th>P(Q=Good)</th>
<th>P(NMR=H | Good)</th>
<th>P(NMR=H | Poor)</th>
<th>Contribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adeq</td>
<td>Avail</td>
<td>0.40</td>
<td>0.35</td>
<td>0.90</td>
<td>0.15</td>
<td>0.70</td>
<td>0.029</td>
</tr>
<tr class="even">
<td>Adeq</td>
<td>Unavail</td>
<td>0.40</td>
<td>0.65</td>
<td>0.60</td>
<td>0.15</td>
<td>0.70</td>
<td>0.097</td>
</tr>
<tr class="odd">
<td>Low</td>
<td>Avail</td>
<td>0.60</td>
<td>0.35</td>
<td>0.50</td>
<td>0.15</td>
<td>0.70</td>
<td>0.089</td>
</tr>
<tr class="even">
<td>Low</td>
<td>Unavail</td>
<td>0.60</td>
<td>0.65</td>
<td>0.15</td>
<td>0.15</td>
<td>0.70</td>
<td>0.240</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>P(NMR=High) = 0.455</strong></p>
<p>Without any evidence, there is a 45.5% baseline probability that a randomly selected district has high neonatal mortality.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Evidence and Updating</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">How observations change our beliefs</span></p>
</section>
<section class="slide level2">
<h2>What Does “Evidence” Mean?</h2>
<div class="definition-box">
<p><strong>Evidence (Observation):</strong> Learning the actual state of one or more variables in the model. Mathematically, this means <em>conditioning</em> the joint distribution on the observed values.</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>Before evidence (prior):</strong></p>
<p><span class="math inline">\(P(\text{Staffing=Low}) = 0.60\)</span></p>
<p>This is our general belief across all districts.</p>
</div>
</div>
<div class="col">
<div class="callout-box orange">
<p><strong>After evidence (posterior):</strong></p>
<p><span class="math inline">\(P(\text{Staffing=Low} \mid \text{NMR=High}) = \; ?\)</span></p>
<p>Observing high NMR in a specific district — what does this tell us about staffing?</p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">
<h2>Bayes’ Rule: The Engine of Updating</h2>
<div class="math-block">
<p><span class="math display">\[P(\text{Staffing=Low} \mid \text{NMR=High}) = \frac{P(\text{NMR=High} \mid \text{Staffing=Low}) \cdot P(\text{Staffing=Low})}{P(\text{NMR=High})}\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 1:</strong> Compute <span class="math inline">\(P(\text{NMR=High} \mid \text{Staffing=Low})\)</span> by marginalizing over Equipment and Quality:</p>
<p><span class="math display">\[P(\text{NMR=H} \mid S=\text{Low}) = \sum_{e,q} P(E=e) \cdot P(Q=q \mid S=\text{Low}, E=e) \cdot P(\text{NMR=H} \mid Q=q) = 0.549\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 2:</strong> Apply Bayes’ rule:</p>
<p><span class="math display">\[P(S=\text{Low} \mid \text{NMR=H}) = \frac{0.549 \times 0.60}{0.455} = 0.724\]</span></p>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>Belief shift:</strong> Observing high NMR increases our belief that staffing is low from <strong>60% → 72.4%</strong>. The evidence makes the “low staffing” explanation more likely.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>The General Pattern of Updating</h2>
<div class="example-block">
<p><span class="example-label">Belief Updating Rule</span></p>
<p>Evidence that is <strong>more likely</strong> under hypothesis A than hypothesis B <strong>increases</strong> our belief in A relative to B. This is the likelihood ratio at work.</p>
</div>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Variable</th>
<th>Prior</th>
<th>Posterior (given NMR=High)</th>
<th>Shift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P(Staffing=Low)</td>
<td>0.60</td>
<td>0.724</td>
<td>+0.124 ↑</td>
</tr>
<tr class="even">
<td>P(Staffing=Adequate)</td>
<td>0.40</td>
<td>0.276</td>
<td>−0.124 ↓</td>
</tr>
<tr class="odd">
<td>P(Equipment=Unavailable)</td>
<td>0.65</td>
<td>0.741</td>
<td>+0.091 ↑</td>
</tr>
<tr class="even">
<td>P(Equipment=Available)</td>
<td>0.35</td>
<td>0.259</td>
<td>−0.091 ↓</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>Both parent nodes shift toward “bad” states</strong> when we observe a bad outcome. But staffing shifts <em>more</em> — suggesting it has a stronger causal connection to NMR in this model.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Inference in Serial Structures</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">A → B → C: Chains and blocking</span></p>
</section>
<section class="slide level2">
<h2>Serial Structure: The Chain</h2>
<div class="definition-box">
<p><strong>Serial Structure (Chain):</strong> A → B → C. Information flows from A through B to C. A and C are <em>marginally dependent</em> but become <strong>conditionally independent given B</strong>.</p>
</div>
<div class="fragment">
<p><strong>MNH Example:</strong></p>
<table style="width: 70%; margin: 0.5em auto; font-size: 0.55em;">
<tbody><tr>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node treatment rect">
Training<br>(T)
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow positive">→ [+]</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node">
Competency<br>(C)
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow negative">→ [−]</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node outcome">
Mortality<br>(M)
</div>
</td>
</tr>
</tbody></table>
</div>
<div class="fragment">
<ul>
<li class="fragment">Training <strong>causes</strong> competency, which <strong>causes</strong> (lower) mortality</li>
<li class="fragment">If we observe competency directly, training gives us <strong>no additional information</strong> about mortality</li>
<li class="fragment">Conditioning on the intermediate node <strong>blocks</strong> the chain</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Serial: CPTs and Priors</h2>
<p><strong>Conditional probability tables for the serial chain:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Training</th>
<th>P(C=High)</th>
<th>P(C=Low)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Completed</td>
<td>0.80</td>
<td>0.20</td>
</tr>
<tr class="even">
<td>Not Completed</td>
<td>0.30</td>
<td>0.70</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Competency</th>
<th>P(M=Low)</th>
<th>P(M=High)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>High</td>
<td>0.85</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>Low</td>
<td>0.35</td>
<td>0.65</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>Prior:</strong> <span class="math inline">\(P(T=\text{Completed}) = 0.50\)</span>, <span class="math inline">\(P(T=\text{Not Completed}) = 0.50\)</span></p>
<p><strong>Marginal competency:</strong></p>
<p><span class="math display">\[P(C=\text{High}) = 0.50 \times 0.80 + 0.50 \times 0.30 = 0.55\]</span></p>
</div>
</section>
<section class="slide level2">
<h2>Serial: Worked Bayesian Calculation</h2>
<p><strong>Scenario:</strong> We observe that Mortality is High. What can we infer about Training?</p>
<div class="fragment">
<p><strong>Step 1:</strong> Marginal <span class="math inline">\(P(M=\text{High})\)</span>:</p>
<p><span class="math display">\[P(M=H) = P(C=H) \cdot P(M=H \mid C=H) + P(C=L) \cdot P(M=H \mid C=L)\]</span> <span class="math display">\[= 0.55 \times 0.15 + 0.45 \times 0.65 = 0.375\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 2:</strong> <span class="math inline">\(P(M=H \mid T=\text{Completed})\)</span>:</p>
<p><span class="math display">\[= 0.80 \times 0.15 + 0.20 \times 0.65 = 0.250\]</span></p>
<p><strong>Step 3:</strong> Bayes’ rule:</p>
<p><span class="math display">\[P(T=\text{Completed} \mid M=H) = \frac{0.250 \times 0.50}{0.375} = 0.333\]</span></p>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>Result:</strong> Observing high mortality shifts our belief about training from 50% → 33.3% completed. High mortality is evidence <em>against</em> training having been completed.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Serial: Blocking by Conditioning</h2>
<p><strong>Now suppose we also know that Competency is Low.</strong> Does Training still matter?</p>
<div class="fragment">
<p><span class="math display">\[P(T=\text{Completed} \mid M=H, C=\text{Low}) = P(T=\text{Completed} \mid C=\text{Low})\]</span></p>
<p>Since <span class="math inline">\(T \perp\!\!\!\perp M \mid C\)</span> in a serial chain, mortality gives <strong>no additional information</strong> once competency is known.</p>
<p><span class="math display">\[P(T=\text{Comp} \mid C=\text{Low}) = \frac{P(C=\text{Low} \mid T=\text{Comp}) \cdot P(T=\text{Comp})}{P(C=\text{Low})} = \frac{0.20 \times 0.50}{0.45} = 0.222\]</span></p>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>Blocking in serial chains:</strong> Once we observe the intermediate node (Competency), the downstream outcome (Mortality) tells us nothing new about the upstream cause (Training). The chain is blocked.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Inference in Diverging Structures</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">A ← B → C: Common cause correlation</span></p>
</section>
<section class="slide level2">
<h2>Diverging Structure: The Fork</h2>
<div class="definition-box">
<p><strong>Diverging Structure (Fork):</strong> A ← B → C. B is a <strong>common cause</strong> of both A and C. A and C are marginally dependent (correlated through B) but become <strong>conditionally independent given B</strong>.</p>
</div>
<div class="fragment">
<p><strong>MNH Example:</strong></p>
<table style="width: 75%; margin: 0.5em auto; font-size: 0.55em;">
<tbody><tr>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node outcome">
PPH<br>Detection
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow positive">← [+]</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node confounder">
Workforce<br>Quality
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow positive">→ [+]</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node outcome">
CPAP<br>Usage
</div>
</td>
</tr>
</tbody></table>
</div>
<div class="fragment">
<ul>
<li class="fragment"><strong>Workforce Quality</strong> drives <em>both</em> PPH detection and CPAP usage</li>
<li class="fragment">PPH detection and CPAP usage are correlated — districts good at one tend to be good at the other</li>
<li class="fragment">This correlation is <strong>not causal</strong> — improving PPH detection does not improve CPAP usage</li>
<li class="fragment">Conditioning on Quality <strong>blocks</strong> the spurious correlation</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Diverging: CPTs and Setup</h2>
<p><strong>CPTs for the diverging structure:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Quality</th>
<th>P(PPH_Det=Good)</th>
<th>P(PPH_Det=Poor)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Good</td>
<td>0.90</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>Poor</td>
<td>0.35</td>
<td>0.65</td>
</tr>
</tbody>
</table>
<table class="caption-top">
<thead>
<tr class="header">
<th>Quality</th>
<th>P(CPAP=Proper)</th>
<th>P(CPAP=Improper)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Good</td>
<td>0.85</td>
<td>0.15</td>
</tr>
<tr class="even">
<td>Poor</td>
<td>0.25</td>
<td>0.75</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>Prior:</strong> <span class="math inline">\(P(Q=\text{Good}) = 0.45\)</span> (from marginal calculation in our model)</p>
<p><strong>Marginals:</strong></p>
<p><span class="math display">\[P(\text{PPH=Good}) = 0.45 \times 0.90 + 0.55 \times 0.35 = 0.598\]</span> <span class="math display">\[P(\text{CPAP=Proper}) = 0.45 \times 0.85 + 0.55 \times 0.25 = 0.520\]</span></p>
</div>
</section>
<section class="slide level2">
<h2>Diverging: Inference from One Child to Another</h2>
<p><strong>Scenario:</strong> We observe PPH Detection is Poor in a district. What does this tell us about CPAP Usage?</p>
<div class="fragment">
<p><strong>Step 1:</strong> Update belief about Quality given PPH=Poor:</p>
<p><span class="math display">\[P(Q=\text{Good} \mid \text{PPH=Poor}) = \frac{0.10 \times 0.45}{0.402} = 0.112\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 2:</strong> Use updated Quality to predict CPAP:</p>
<p><span class="math display">\[P(\text{CPAP=Proper} \mid \text{PPH=Poor}) = 0.112 \times 0.85 + 0.888 \times 0.25 = 0.317\]</span></p>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>Result:</strong> Observing poor PPH detection drops our belief that CPAP usage is proper from <strong>52.0% → 31.7%</strong>. Information flows from one effect to another through the common cause — even though there is no direct causal link.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Diverging: Blocking by Conditioning on Common Cause</h2>
<p><strong>Now suppose we know that Quality is Good.</strong> Does PPH detection still tell us about CPAP?</p>
<div class="fragment">
<p><span class="math display">\[P(\text{CPAP=Proper} \mid \text{PPH=Poor}, Q=\text{Good}) = P(\text{CPAP=Proper} \mid Q=\text{Good}) = 0.85\]</span></p>
<p>Since <span class="math inline">\(\text{PPH} \perp\!\!\!\perp \text{CPAP} \mid Q\)</span> in a diverging structure, PPH detection is <strong>irrelevant</strong> once we know Quality.</p>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>Blocking in diverging structures:</strong> Once we observe the common cause (Quality), knowing one effect (PPH Detection) tells us nothing about the other effect (CPAP Usage). The fork is blocked.</p>
</div>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>Management implication:</strong> If you can directly measure workforce quality, you don’t need to infer it from proxy indicators. Direct measurement blocks the indirect reasoning path and gives sharper diagnoses.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Inference in Converging Structures</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">A → B ← C: The explaining away phenomenon</span></p>
</section>
<section class="slide level2">
<h2>Converging Structure: The Collider</h2>
<div class="definition-box">
<p><strong>Converging Structure (Collider):</strong> A → B ← C. B is a <strong>common effect</strong> of A and C. Unlike serial and diverging structures, A and C are <em>marginally independent</em> but become <strong>dependent when we condition on B</strong>. This is the most counterintuitive pattern in causal reasoning.</p>
</div>
<div class="fragment">
<p><strong>MNH Example:</strong></p>
<table style="width: 75%; margin: 0.5em auto; font-size: 0.55em;">
<tbody><tr>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node treatment rect">
Staffing<br>(S)
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow positive">→ [+]</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node">
Workforce<br>Quality (Q)
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow positive">← [+]</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node treatment rect">
Equipment<br>(E)
</div>
</td>
</tr>
</tbody></table>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>The counterintuitive part:</strong> Staffing and Equipment are <em>independent</em> causes — knowing one tells you nothing about the other. <strong>But</strong> once we observe their common effect (Quality), they become dependent. Learning about one <em>changes</em> our belief about the other.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Explaining Away: The Core Idea</h2>
<div class="example-block">
<p><span class="example-label">The Explaining Away Intuition</span></p>
<p><strong>Scenario:</strong> You observe that a district has <strong>Good</strong> workforce quality. This is surprising — it could be because staffing is adequate, OR because equipment is available, OR both.</p>
<p><strong>Now you learn</strong> that staffing is <strong>Low</strong>. What happens to your belief about equipment?</p>
<p><strong>Answer:</strong> Equipment must be <strong>Available</strong> — because <em>something</em> has to explain the good quality, and staffing can’t be the explanation. Equipment “explains away” what staffing cannot.</p>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>This is called “explaining away”:</strong> When two independent causes compete to explain the same effect, confirming one cause makes the other <em>less</em> likely (and disconfirming one makes the other <em>more</em> likely).</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Converging: Worked Calculation</h2>
<p><strong>CPT for Quality (from our model):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Staffing</th>
<th>Equipment</th>
<th>P(Q=Good)</th>
<th>P(Q=Poor)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adequate</td>
<td>Available</td>
<td>0.90</td>
<td>0.10</td>
</tr>
<tr class="even">
<td>Adequate</td>
<td>Unavailable</td>
<td>0.60</td>
<td>0.40</td>
</tr>
<tr class="odd">
<td>Low</td>
<td>Available</td>
<td>0.50</td>
<td>0.50</td>
</tr>
<tr class="even">
<td>Low</td>
<td>Unavailable</td>
<td>0.15</td>
<td>0.85</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p><strong>Step 1:</strong> Observe Q=Good. Update belief about Equipment:</p>
<p><span class="math display">\[P(E=\text{Avail} \mid Q=\text{Good}) = \frac{P(Q=\text{Good} \mid E=\text{Avail}) \cdot P(E=\text{Avail})}{P(Q=\text{Good})}\]</span></p>
<p><span class="math display">\[P(Q=\text{Good} \mid E=\text{Avail}) = 0.40 \times 0.90 + 0.60 \times 0.50 = 0.660\]</span></p>
<p><span class="math display">\[P(Q=\text{Good}) = 0.35 \times 0.660 + 0.65 \times (0.40 \times 0.60 + 0.60 \times 0.15) = 0.35 \times 0.660 + 0.65 \times 0.330 = 0.446\]</span></p>
<p><span class="math display">\[P(E=\text{Avail} \mid Q=\text{Good}) = \frac{0.660 \times 0.35}{0.446} = 0.518\]</span></p>
</div>
</section>
<section class="slide level2">
<h2>Converging: The Explaining Away Effect</h2>
<p><strong>Step 2:</strong> Now <em>also</em> observe S=Low. Update belief about Equipment:</p>
<p><span class="math display">\[P(E=\text{Avail} \mid Q=\text{Good}, S=\text{Low}) = \frac{P(Q=\text{Good} \mid S=\text{Low}, E=\text{Avail}) \cdot P(E=\text{Avail})}{P(Q=\text{Good} \mid S=\text{Low})}\]</span></p>
<p><span class="math display">\[P(Q=\text{Good} \mid S=\text{Low}) = 0.35 \times 0.50 + 0.65 \times 0.15 = 0.273\]</span></p>
<p><span class="math display">\[P(E=\text{Avail} \mid Q=\text{Good}, S=\text{Low}) = \frac{0.50 \times 0.35}{0.273} = 0.642\]</span></p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Condition</th>
<th>P(Equipment=Available)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Prior</strong> (no evidence)</td>
<td>0.350</td>
</tr>
<tr class="even">
<td><strong>Given Q=Good</strong></td>
<td>0.518</td>
</tr>
<tr class="odd">
<td><strong>Given Q=Good AND S=Low</strong></td>
<td>0.642</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>Explaining away in action:</strong> Learning that staffing is low — when quality is good — <em>increases</em> our belief that equipment must be available from 51.8% to 64.2%. Equipment must be compensating for the staffing deficit.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>MNH Application: District Diagnosis</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">A complete worked example with realistic data</span></p>
</section>
<section class="slide level2">
<h2>The Diagnostic Scenario</h2>
<div class="callout-box red">
<p><strong>Alert:</strong> District Mwanga reports a neonatal mortality rate of 35 per 1,000 live births — well above the national average of 25 per 1,000. The Beginnings Fund country director asks: <strong>What is most likely going wrong?</strong></p>
</div>
<div class="fragment">
<p><strong>Available evidence:</strong></p>
<ul>
<li class="fragment">NMR = High (35/1,000 vs.&nbsp;target of 25/1,000)</li>
<li class="fragment">No direct observation of staffing, equipment, training, or quality</li>
<li class="fragment">We have the national-level causal model with CPTs</li>
</ul>
</div>
<div class="fragment">
<p><strong>Our task:</strong> Use Bayesian inference to update beliefs about <em>all</em> parent nodes, identify the most likely root cause, and recommend targeted investigation.</p>
</div>
</section>
<section class="slide level2">
<h2>Step 1: Establish the Full Model</h2>
<table style="width: 90%; margin: 0.3em auto; font-size: 0.42em;">
<tbody><tr>
<td style="text-align: center; padding: 0.4em;">
<div class="dag-node treatment rect">
Staffing (S)<br>P(Adeq)=0.40
</div>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.4em;">
<div class="dag-node treatment rect">
Equipment (E)<br>P(Avail)=0.35
</div>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.4em;">
<div class="dag-node treatment rect">
Training (T)<br>P(Comp)=0.50
</div>
</td>
</tr>
<tr>
<td style="text-align: center;">
<span class="dag-arrow">↘</span>
</td>
<td>
</td>
<td style="text-align: center;">
<span class="dag-arrow">↓</span>
</td>
<td>
</td>
<td style="text-align: center;">
<span class="dag-arrow">↙</span>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.4em;">
<div class="dag-node">
Quality (Q)
</div>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td style="text-align: center;">
<span class="dag-arrow">↓</span>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.4em;">
<div class="dag-node outcome">
NMR
</div>
</td>
<td>
</td>
<td>
</td>
</tr>
</tbody></table>
<div class="fragment">
<p><strong>Extended CPT for Quality (adding Training):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>S</th>
<th>E</th>
<th>T</th>
<th>P(Q=Good)</th>
<th>P(Q=Poor)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Adeq</td>
<td>Avail</td>
<td>Comp</td>
<td>0.95</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>Adeq</td>
<td>Avail</td>
<td>Not</td>
<td>0.80</td>
<td>0.20</td>
</tr>
<tr class="odd">
<td>Adeq</td>
<td>Unavail</td>
<td>Comp</td>
<td>0.65</td>
<td>0.35</td>
</tr>
<tr class="even">
<td>Adeq</td>
<td>Unavail</td>
<td>Not</td>
<td>0.45</td>
<td>0.55</td>
</tr>
<tr class="odd">
<td>Low</td>
<td>Avail</td>
<td>Comp</td>
<td>0.55</td>
<td>0.45</td>
</tr>
<tr class="even">
<td>Low</td>
<td>Avail</td>
<td>Not</td>
<td>0.35</td>
<td>0.65</td>
</tr>
<tr class="odd">
<td>Low</td>
<td>Unavail</td>
<td>Comp</td>
<td>0.20</td>
<td>0.80</td>
</tr>
<tr class="even">
<td>Low</td>
<td>Unavail</td>
<td>Not</td>
<td>0.08</td>
<td>0.92</td>
</tr>
</tbody>
</table>
</div>
</section>
<section class="slide level2">
<h2>Step 2: Compute Posterior Probabilities</h2>
<p>Given NMR=High, we apply Bayes’ rule to each root node:</p>
<div class="fragment">
<div class="math-block">
<p><span class="math display">\[P(S=\text{Low} \mid \text{NMR=H}) = \frac{\sum_{e,t,q} P(S=\text{Low}) \cdot P(E=e) \cdot P(T=t) \cdot P(Q=q \mid S=\text{Low},e,t) \cdot P(\text{NMR=H} \mid q)}{P(\text{NMR=H})}\]</span></p>
</div>
</div>
<div class="fragment">
<p><strong>Results (computed across all 8 parent combinations):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Root Node</th>
<th>Prior</th>
<th>Posterior (NMR=High)</th>
<th>Shift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P(Staffing=Low)</td>
<td>0.600</td>
<td>0.710</td>
<td><strong>+0.110 ↑</strong></td>
</tr>
<tr class="even">
<td>P(Equipment=Unavail)</td>
<td>0.650</td>
<td>0.738</td>
<td><strong>+0.088 ↑</strong></td>
</tr>
<tr class="odd">
<td>P(Training=Not Comp)</td>
<td>0.500</td>
<td>0.573</td>
<td><strong>+0.073 ↑</strong></td>
</tr>
<tr class="even">
<td>P(Quality=Poor)</td>
<td>—</td>
<td>0.682</td>
<td>—</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>Staffing has the largest posterior shift</strong> — it moves from 60% to 71%. This suggests staffing is the most informative variable to investigate first in District Mwanga.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Step 3: Identify the Most Likely Configuration</h2>
<p>Which combination of root causes is most probable given NMR=High?</p>
<div class="fragment">
<p><strong>Top 4 configurations (posterior probability):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Rank</th>
<th>Staffing</th>
<th>Equipment</th>
<th>Training</th>
<th>P(config | NMR=H)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>1</strong></td>
<td>Low</td>
<td>Unavailable</td>
<td>Not Comp</td>
<td><strong>0.284</strong></td>
</tr>
<tr class="even">
<td>2</td>
<td>Low</td>
<td>Unavailable</td>
<td>Completed</td>
<td>0.194</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Low</td>
<td>Available</td>
<td>Not Comp</td>
<td>0.098</td>
</tr>
<tr class="even">
<td>4</td>
<td>Adequate</td>
<td>Unavailable</td>
<td>Not Comp</td>
<td>0.087</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>Most likely diagnosis:</strong> All three root causes are in their “bad” state — low staffing, unavailable equipment, incomplete training. This configuration is 2.8x more likely than the second-ranked option.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Step 4: Compare with a “Healthy” District</h2>
<p><strong>District Songea reports NMR=Low (18/1,000).</strong> How do beliefs differ?</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Root Node</th>
<th>Prior</th>
<th>Posterior (NMR=High)</th>
<th>Posterior (NMR=Low)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>P(Staffing=Low)</td>
<td>0.600</td>
<td>0.710</td>
<td>0.508</td>
</tr>
<tr class="even">
<td>P(Equip=Unavail)</td>
<td>0.650</td>
<td>0.738</td>
<td>0.576</td>
</tr>
<tr class="odd">
<td>P(Training=Not Comp)</td>
<td>0.500</td>
<td>0.573</td>
<td>0.439</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box red">
<p><strong>District Mwanga (NMR=High)</strong></p>
<p>All causes shift toward bad states. Staffing is the strongest signal. Recommend immediate staffing audit.</p>
</div>
</div>
<div class="col">
<div class="callout-box green">
<p><strong>District Songea (NMR=Low)</strong></p>
<p>All causes shift toward good states. Equipment shows the most improvement. This district is likely well-resourced.</p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>The power of the model:</strong> The same framework that diagnoses problems also identifies what’s working well. Both directions inform resource allocation.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>R Code Workshop</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Bayesian inference with bnlearn</span></p>
</section>
<section class="slide level2">
<h2>R Block 1: Build a BN with CPTs</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">library</span>(bnlearn)</span>
<span id="cb1-2"><a href=""></a><span class="fu">library</span>(gRain)</span>
<span id="cb1-3"><a href=""></a></span>
<span id="cb1-4"><a href=""></a><span class="co"># Define the DAG structure</span></span>
<span id="cb1-5"><a href=""></a>dag <span class="ot">&lt;-</span> <span class="fu">model2network</span>(<span class="st">"[Staffing][Equipment][Training][Quality|Staffing:Equipment:Training][NMR|Quality]"</span>)</span>
<span id="cb1-6"><a href=""></a></span>
<span id="cb1-7"><a href=""></a><span class="co"># Define CPTs</span></span>
<span id="cb1-8"><a href=""></a>cpt_s <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.40</span>, <span class="fl">0.60</span>), <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb1-9"><a href=""></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, <span class="fu">c</span>(<span class="st">"Adequate"</span>, <span class="st">"Low"</span>)))</span>
<span id="cb1-10"><a href=""></a></span>
<span id="cb1-11"><a href=""></a>cpt_e <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.35</span>, <span class="fl">0.65</span>), <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb1-12"><a href=""></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, <span class="fu">c</span>(<span class="st">"Available"</span>, <span class="st">"Unavailable"</span>)))</span>
<span id="cb1-13"><a href=""></a></span>
<span id="cb1-14"><a href=""></a>cpt_t <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.50</span>), <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb1-15"><a href=""></a>                <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="cn">NULL</span>, <span class="fu">c</span>(<span class="st">"Completed"</span>, <span class="st">"Not_Completed"</span>)))</span>
<span id="cb1-16"><a href=""></a></span>
<span id="cb1-17"><a href=""></a><span class="co"># Quality CPT: P(Quality | Staffing, Equipment, Training)</span></span>
<span id="cb1-18"><a href=""></a>cpt_q <span class="ot">&lt;-</span> <span class="fu">array</span>(</span>
<span id="cb1-19"><a href=""></a>  <span class="fu">c</span>(<span class="fl">0.95</span>, <span class="fl">0.05</span>,  <span class="co"># S=Adeq, E=Avail, T=Comp</span></span>
<span id="cb1-20"><a href=""></a>    <span class="fl">0.80</span>, <span class="fl">0.20</span>,  <span class="co"># S=Adeq, E=Avail, T=Not</span></span>
<span id="cb1-21"><a href=""></a>    <span class="fl">0.65</span>, <span class="fl">0.35</span>,  <span class="co"># S=Adeq, E=Unavail, T=Comp</span></span>
<span id="cb1-22"><a href=""></a>    <span class="fl">0.45</span>, <span class="fl">0.55</span>,  <span class="co"># S=Adeq, E=Unavail, T=Not</span></span>
<span id="cb1-23"><a href=""></a>    <span class="fl">0.55</span>, <span class="fl">0.45</span>,  <span class="co"># S=Low, E=Avail, T=Comp</span></span>
<span id="cb1-24"><a href=""></a>    <span class="fl">0.35</span>, <span class="fl">0.65</span>,  <span class="co"># S=Low, E=Avail, T=Not</span></span>
<span id="cb1-25"><a href=""></a>    <span class="fl">0.20</span>, <span class="fl">0.80</span>,  <span class="co"># S=Low, E=Unavail, T=Comp</span></span>
<span id="cb1-26"><a href=""></a>    <span class="fl">0.08</span>, <span class="fl">0.92</span>), <span class="co"># S=Low, E=Unavail, T=Not</span></span>
<span id="cb1-27"><a href=""></a>  <span class="at">dim =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>),</span>
<span id="cb1-28"><a href=""></a>  <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="at">Quality =</span> <span class="fu">c</span>(<span class="st">"Good"</span>, <span class="st">"Poor"</span>),</span>
<span id="cb1-29"><a href=""></a>                  <span class="at">Staffing =</span> <span class="fu">c</span>(<span class="st">"Adequate"</span>, <span class="st">"Low"</span>),</span>
<span id="cb1-30"><a href=""></a>                  <span class="at">Equipment =</span> <span class="fu">c</span>(<span class="st">"Available"</span>, <span class="st">"Unavailable"</span>),</span>
<span id="cb1-31"><a href=""></a>                  <span class="at">Training =</span> <span class="fu">c</span>(<span class="st">"Completed"</span>, <span class="st">"Not_Completed"</span>)))</span>
<span id="cb1-32"><a href=""></a></span>
<span id="cb1-33"><a href=""></a><span class="co"># NMR CPT: P(NMR | Quality)</span></span>
<span id="cb1-34"><a href=""></a>cpt_nmr <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="fl">0.85</span>, <span class="fl">0.15</span>, <span class="fl">0.30</span>, <span class="fl">0.70</span>), <span class="at">ncol =</span> <span class="dv">2</span>,</span>
<span id="cb1-35"><a href=""></a>                  <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="at">NMR =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"High"</span>),</span>
<span id="cb1-36"><a href=""></a>                                  <span class="at">Quality =</span> <span class="fu">c</span>(<span class="st">"Good"</span>, <span class="st">"Poor"</span>)))</span>
<span id="cb1-37"><a href=""></a></span>
<span id="cb1-38"><a href=""></a><span class="co"># Fit the BN with custom CPTs</span></span>
<span id="cb1-39"><a href=""></a>bn_fit <span class="ot">&lt;-</span> <span class="fu">custom.fit</span>(dag, <span class="fu">list</span>(</span>
<span id="cb1-40"><a href=""></a>  <span class="at">Staffing =</span> cpt_s, <span class="at">Equipment =</span> cpt_e, <span class="at">Training =</span> cpt_t,</span>
<span id="cb1-41"><a href=""></a>  <span class="at">Quality =</span> cpt_q, <span class="at">NMR =</span> cpt_nmr))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 2: Query with Evidence</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># --- Marginal probability (no evidence) ---</span></span>
<span id="cb2-2"><a href=""></a><span class="fu">cpquery</span>(bn_fit,</span>
<span id="cb2-3"><a href=""></a>        <span class="at">event =</span> (NMR <span class="sc">==</span> <span class="st">"High"</span>),</span>
<span id="cb2-4"><a href=""></a>        <span class="at">evidence =</span> <span class="cn">TRUE</span>,</span>
<span id="cb2-5"><a href=""></a>        <span class="at">n =</span> <span class="fl">1e6</span>)</span>
<span id="cb2-6"><a href=""></a><span class="co"># ≈ 0.455</span></span>
<span id="cb2-7"><a href=""></a></span>
<span id="cb2-8"><a href=""></a><span class="co"># --- Posterior with evidence: NMR is High ---</span></span>
<span id="cb2-9"><a href=""></a><span class="co"># What is P(Staffing = Low | NMR = High)?</span></span>
<span id="cb2-10"><a href=""></a><span class="fu">cpquery</span>(bn_fit,</span>
<span id="cb2-11"><a href=""></a>        <span class="at">event =</span> (Staffing <span class="sc">==</span> <span class="st">"Low"</span>),</span>
<span id="cb2-12"><a href=""></a>        <span class="at">evidence =</span> (NMR <span class="sc">==</span> <span class="st">"High"</span>),</span>
<span id="cb2-13"><a href=""></a>        <span class="at">n =</span> <span class="fl">1e6</span>)</span>
<span id="cb2-14"><a href=""></a><span class="co"># ≈ 0.71</span></span>
<span id="cb2-15"><a href=""></a></span>
<span id="cb2-16"><a href=""></a><span class="co"># --- Evidence on a root node ---</span></span>
<span id="cb2-17"><a href=""></a><span class="co"># What is P(NMR = High | Staffing = Low)?</span></span>
<span id="cb2-18"><a href=""></a><span class="fu">cpquery</span>(bn_fit,</span>
<span id="cb2-19"><a href=""></a>        <span class="at">event =</span> (NMR <span class="sc">==</span> <span class="st">"High"</span>),</span>
<span id="cb2-20"><a href=""></a>        <span class="at">evidence =</span> (Staffing <span class="sc">==</span> <span class="st">"Low"</span>),</span>
<span id="cb2-21"><a href=""></a>        <span class="at">n =</span> <span class="fl">1e6</span>)</span>
<span id="cb2-22"><a href=""></a><span class="co"># ≈ 0.55</span></span>
<span id="cb2-23"><a href=""></a></span>
<span id="cb2-24"><a href=""></a><span class="co"># --- Multiple pieces of evidence ---</span></span>
<span id="cb2-25"><a href=""></a><span class="co"># P(NMR = High | Staffing = Low, Equipment = Unavailable)</span></span>
<span id="cb2-26"><a href=""></a><span class="fu">cpquery</span>(bn_fit,</span>
<span id="cb2-27"><a href=""></a>        <span class="at">event =</span> (NMR <span class="sc">==</span> <span class="st">"High"</span>),</span>
<span id="cb2-28"><a href=""></a>        <span class="at">evidence =</span> (Staffing <span class="sc">==</span> <span class="st">"Low"</span> <span class="sc">&amp;</span> Equipment <span class="sc">==</span> <span class="st">"Unavailable"</span>),</span>
<span id="cb2-29"><a href=""></a>        <span class="at">n =</span> <span class="fl">1e6</span>)</span>
<span id="cb2-30"><a href=""></a><span class="co"># ≈ 0.63</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 3: Compare Posterior vs.&nbsp;Prior</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="co"># Function to compute posteriors for all root nodes given NMR evidence</span></span>
<span id="cb3-2"><a href=""></a>compute_posteriors <span class="ot">&lt;-</span> <span class="cf">function</span>(bn, nmr_state, <span class="at">n_samples =</span> <span class="fl">1e6</span>) {</span>
<span id="cb3-3"><a href=""></a>  <span class="fu">data.frame</span>(</span>
<span id="cb3-4"><a href=""></a>    <span class="at">Variable =</span> <span class="fu">c</span>(<span class="st">"Staffing=Low"</span>, <span class="st">"Equipment=Unavail"</span>, <span class="st">"Training=Not_Comp"</span>),</span>
<span id="cb3-5"><a href=""></a>    <span class="at">Prior =</span> <span class="fu">c</span>(<span class="fl">0.60</span>, <span class="fl">0.65</span>, <span class="fl">0.50</span>),</span>
<span id="cb3-6"><a href=""></a>    <span class="at">Posterior =</span> <span class="fu">c</span>(</span>
<span id="cb3-7"><a href=""></a>      <span class="fu">cpquery</span>(bn, (Staffing <span class="sc">==</span> <span class="st">"Low"</span>), (NMR <span class="sc">==</span> nmr_state), <span class="at">n =</span> n_samples),</span>
<span id="cb3-8"><a href=""></a>      <span class="fu">cpquery</span>(bn, (Equipment <span class="sc">==</span> <span class="st">"Unavailable"</span>), (NMR <span class="sc">==</span> nmr_state), <span class="at">n =</span> n_samples),</span>
<span id="cb3-9"><a href=""></a>      <span class="fu">cpquery</span>(bn, (Training <span class="sc">==</span> <span class="st">"Not_Completed"</span>), (NMR <span class="sc">==</span> nmr_state), <span class="at">n =</span> n_samples)</span>
<span id="cb3-10"><a href=""></a>    )</span>
<span id="cb3-11"><a href=""></a>  )</span>
<span id="cb3-12"><a href=""></a>}</span>
<span id="cb3-13"><a href=""></a></span>
<span id="cb3-14"><a href=""></a><span class="co"># Posteriors given NMR=High (District Mwanga)</span></span>
<span id="cb3-15"><a href=""></a>post_high <span class="ot">&lt;-</span> <span class="fu">compute_posteriors</span>(bn_fit, <span class="st">"High"</span>)</span>
<span id="cb3-16"><a href=""></a>post_high<span class="sc">$</span>Shift <span class="ot">&lt;-</span> post_high<span class="sc">$</span>Posterior <span class="sc">-</span> post_high<span class="sc">$</span>Prior</span>
<span id="cb3-17"><a href=""></a><span class="fu">print</span>(post_high)</span>
<span id="cb3-18"><a href=""></a></span>
<span id="cb3-19"><a href=""></a><span class="co"># Posteriors given NMR=Low (District Songea)</span></span>
<span id="cb3-20"><a href=""></a>post_low <span class="ot">&lt;-</span> <span class="fu">compute_posteriors</span>(bn_fit, <span class="st">"Low"</span>)</span>
<span id="cb3-21"><a href=""></a>post_low<span class="sc">$</span>Shift <span class="ot">&lt;-</span> post_low<span class="sc">$</span>Posterior <span class="sc">-</span> post_low<span class="sc">$</span>Prior</span>
<span id="cb3-22"><a href=""></a><span class="fu">print</span>(post_low)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 4: Visualize Belief Updating</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href=""></a><span class="fu">library</span>(tidyr)</span>
<span id="cb4-3"><a href=""></a></span>
<span id="cb4-4"><a href=""></a><span class="co"># Combine prior and posterior into tidy format</span></span>
<span id="cb4-5"><a href=""></a>viz_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-6"><a href=""></a>  <span class="at">Variable =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Staffing</span><span class="sc">\n</span><span class="st">(Low)"</span>, <span class="st">"Equipment</span><span class="sc">\n</span><span class="st">(Unavail)"</span>, <span class="st">"Training</span><span class="sc">\n</span><span class="st">(Not Comp)"</span>), <span class="dv">2</span>),</span>
<span id="cb4-7"><a href=""></a>  <span class="at">Condition =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Prior"</span>, <span class="st">"Posterior</span><span class="sc">\n</span><span class="st">(NMR=High)"</span>), <span class="at">each =</span> <span class="dv">3</span>),</span>
<span id="cb4-8"><a href=""></a>  <span class="at">Probability =</span> <span class="fu">c</span>(</span>
<span id="cb4-9"><a href=""></a>    <span class="fl">0.60</span>, <span class="fl">0.65</span>, <span class="fl">0.50</span>,          <span class="co"># Priors</span></span>
<span id="cb4-10"><a href=""></a>    <span class="fl">0.710</span>, <span class="fl">0.738</span>, <span class="fl">0.573</span>         <span class="co"># Posteriors given NMR=High</span></span>
<span id="cb4-11"><a href=""></a>  )</span>
<span id="cb4-12"><a href=""></a>)</span>
<span id="cb4-13"><a href=""></a>viz_data<span class="sc">$</span>Condition <span class="ot">&lt;-</span> <span class="fu">factor</span>(viz_data<span class="sc">$</span>Condition,</span>
<span id="cb4-14"><a href=""></a>                              <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Prior"</span>, <span class="st">"Posterior</span><span class="sc">\n</span><span class="st">(NMR=High)"</span>))</span>
<span id="cb4-15"><a href=""></a></span>
<span id="cb4-16"><a href=""></a><span class="fu">ggplot</span>(viz_data, <span class="fu">aes</span>(<span class="at">x =</span> Variable, <span class="at">y =</span> Probability, <span class="at">fill =</span> Condition)) <span class="sc">+</span></span>
<span id="cb4-17"><a href=""></a>  <span class="fu">geom_col</span>(<span class="at">position =</span> <span class="st">"dodge"</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb4-18"><a href=""></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.1f%%"</span>, Probability <span class="sc">*</span> <span class="dv">100</span>)),</span>
<span id="cb4-19"><a href=""></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.6</span>), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>, <span class="at">size =</span> <span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb4-20"><a href=""></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Prior"</span> <span class="ot">=</span> <span class="st">"#00A1DF"</span>, <span class="st">"Posterior</span><span class="sc">\n</span><span class="st">(NMR=High)"</span> <span class="ot">=</span> <span class="st">"#E24A3F"</span>),</span>
<span id="cb4-21"><a href=""></a>                    <span class="at">name =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb4-22"><a href=""></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb4-23"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Belief Updating: Prior vs. Posterior Given NMR = High"</span>,</span>
<span id="cb4-24"><a href=""></a>       <span class="at">subtitle =</span> <span class="st">"All 'bad' states become more likely after observing high mortality"</span>,</span>
<span id="cb4-25"><a href=""></a>       <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Probability"</span>) <span class="sc">+</span></span>
<span id="cb4-26"><a href=""></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb4-27"><a href=""></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb4-28"><a href=""></a>        <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">color =</span> <span class="st">"#005CB9"</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 5: Full District Diagnosis Workflow</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="co"># ---- Full diagnosis workflow for a district ----</span></span>
<span id="cb5-2"><a href=""></a></span>
<span id="cb5-3"><a href=""></a>diagnose_district <span class="ot">&lt;-</span> <span class="cf">function</span>(bn, evidence_list, <span class="at">n_samples =</span> <span class="fl">1e6</span>) {</span>
<span id="cb5-4"><a href=""></a>  <span class="co"># Build evidence string</span></span>
<span id="cb5-5"><a href=""></a>  ev_expr <span class="ot">&lt;-</span> <span class="fu">paste</span>(<span class="fu">names</span>(evidence_list), <span class="st">"=="</span>,</span>
<span id="cb5-6"><a href=""></a>                   <span class="fu">paste0</span>(<span class="st">'"'</span>, evidence_list, <span class="st">'"'</span>), <span class="at">collapse =</span> <span class="st">" &amp; "</span>)</span>
<span id="cb5-7"><a href=""></a></span>
<span id="cb5-8"><a href=""></a>  <span class="co"># Query each root node</span></span>
<span id="cb5-9"><a href=""></a>  results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-10"><a href=""></a>    <span class="at">Node =</span> <span class="fu">c</span>(<span class="st">"Staffing"</span>, <span class="st">"Equipment"</span>, <span class="st">"Training"</span>),</span>
<span id="cb5-11"><a href=""></a>    <span class="at">Bad_State =</span> <span class="fu">c</span>(<span class="st">"Low"</span>, <span class="st">"Unavailable"</span>, <span class="st">"Not_Completed"</span>),</span>
<span id="cb5-12"><a href=""></a>    <span class="at">Prior =</span> <span class="fu">c</span>(<span class="fl">0.60</span>, <span class="fl">0.65</span>, <span class="fl">0.50</span>)</span>
<span id="cb5-13"><a href=""></a>  )</span>
<span id="cb5-14"><a href=""></a></span>
<span id="cb5-15"><a href=""></a>  results<span class="sc">$</span>Posterior <span class="ot">&lt;-</span> <span class="fu">sapply</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(results), <span class="cf">function</span>(i) {</span>
<span id="cb5-16"><a href=""></a>    <span class="fu">cpquery</span>(bn,</span>
<span id="cb5-17"><a href=""></a>            <span class="at">event =</span> <span class="fu">eval</span>(<span class="fu">parse</span>(<span class="at">text =</span> <span class="fu">paste0</span>(results<span class="sc">$</span>Node[i], <span class="st">' == "'</span>,</span>
<span id="cb5-18"><a href=""></a>                                              results<span class="sc">$</span>Bad_State[i], <span class="st">'"'</span>))),</span>
<span id="cb5-19"><a href=""></a>            <span class="at">evidence =</span> <span class="fu">eval</span>(<span class="fu">parse</span>(<span class="at">text =</span> ev_expr)),</span>
<span id="cb5-20"><a href=""></a>            <span class="at">n =</span> n_samples)</span>
<span id="cb5-21"><a href=""></a>  })</span>
<span id="cb5-22"><a href=""></a></span>
<span id="cb5-23"><a href=""></a>  results<span class="sc">$</span>Shift <span class="ot">&lt;-</span> results<span class="sc">$</span>Posterior <span class="sc">-</span> results<span class="sc">$</span>Prior</span>
<span id="cb5-24"><a href=""></a>  results<span class="sc">$</span>Priority <span class="ot">&lt;-</span> <span class="fu">rank</span>(<span class="sc">-</span><span class="fu">abs</span>(results<span class="sc">$</span>Shift))</span>
<span id="cb5-25"><a href=""></a>  results[<span class="fu">order</span>(results<span class="sc">$</span>Priority), ]</span>
<span id="cb5-26"><a href=""></a>}</span>
<span id="cb5-27"><a href=""></a></span>
<span id="cb5-28"><a href=""></a><span class="co"># Diagnose District Mwanga (NMR=High)</span></span>
<span id="cb5-29"><a href=""></a><span class="fu">cat</span>(<span class="st">"=== District Mwanga Diagnosis ===</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-30"><a href=""></a>mwanga <span class="ot">&lt;-</span> <span class="fu">diagnose_district</span>(bn_fit, <span class="fu">list</span>(<span class="at">NMR =</span> <span class="st">"High"</span>))</span>
<span id="cb5-31"><a href=""></a><span class="fu">print</span>(mwanga)</span>
<span id="cb5-32"><a href=""></a></span>
<span id="cb5-33"><a href=""></a><span class="co"># Diagnose with additional evidence (NMR=High, Quality=Poor)</span></span>
<span id="cb5-34"><a href=""></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">=== With additional evidence: Quality=Poor ===</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-35"><a href=""></a>mwanga_deep <span class="ot">&lt;-</span> <span class="fu">diagnose_district</span>(bn_fit,</span>
<span id="cb5-36"><a href=""></a>                                  <span class="fu">list</span>(<span class="at">NMR =</span> <span class="st">"High"</span>, <span class="at">Quality =</span> <span class="st">"Poor"</span>))</span>
<span id="cb5-37"><a href=""></a><span class="fu">print</span>(mwanga_deep)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>Key Takeaways</h2>
<div class="key-takeaway">
<p><strong>Marginal probabilities</strong> tell us baseline expectations. The marginal P(NMR=High) = 45.5% is the starting point before any district-specific evidence.</p>
<p><strong>Evidence updates beliefs via Bayes’ rule.</strong> Observing NMR=High shifts all root causes toward their “bad” states — with staffing showing the largest shift.</p>
<p><strong>The three structures determine information flow:</strong> serial and diverging chains are blocked by conditioning on the middle node; converging chains are <em>activated</em> by it.</p>
<p><strong>Explaining away is the most counterintuitive phenomenon.</strong> In a collider, observing the common effect makes independent causes compete — confirming one reduces belief in the other.</p>
</div>
</section>
<section class="slide level2">
<h2>Looking Ahead</h2>
<div class="callout-box">
<p><strong>Next: Chapter 6 — Simpson’s Paradox and Cost-Effectiveness</strong></p>
<p>Now that we can perform inference, we apply it to a critical problem:</p>
<ul>
<li><strong>Simpson’s Paradox</strong> — when aggregate data reverses the true causal effect</li>
<li>How conditioning on the wrong variable produces misleading cost-effectiveness estimates</li>
<li>Why program evaluation in MNH requires causal reasoning, not just data analysis</li>
<li>Practical implications for how the Beginnings Fund evaluates its $525M portfolio</li>
</ul>
</div>
</section>
<section class="slide level2" data-background-color="white">
<h2></h2>
<p><br><br><br></p>
<div style="text-align: center;">
<p><img data-src="bka-logo.png" width="250"></p>
<p><br></p>
<p><span style="color: #005CB9; font-size: 0.6em;">Inference and Intervention | Chapter 5: Situational Analysis</span></p>
<p><span style="color: #666; font-size: 0.5em;">BK Advisors</span></p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="bka-logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'slide',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>