<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="BK Advisors">
  <meta name="dcterms.date" content="2026-02-12">
  <title>Chapter 6: Modeling MNH Cost-Effectiveness</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-afce544662d4c774d79a6cccbbed54ef.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section data-background-color="#005CB9" class="quarto-title-block center">
  <h1 class="title">Chapter 6: Modeling MNH Cost-Effectiveness</h1>
  <p class="subtitle">Inference and Intervention | BK Advisors</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
BK Advisors 
</div>
</div>
</div>

  <p class="date">2026-02-12</p>
</section>
<section class="slide level2">
<h2>Learning Objectives</h2>
<p>After this chapter, you will be able to:</p>
<ul>
<li class="fragment">Identify <strong>Simpson’s Paradox</strong> and explain why aggregated data can reverse the direction of causal effects</li>
<li class="fragment">Avoid the <strong>Prosecutor’s Fallacy</strong> by applying Bayes’ rule to distinguish <span class="math inline">\(P(\text{Evidence} \mid \text{Hypothesis})\)</span> from <span class="math inline">\(P(\text{Hypothesis} \mid \text{Evidence})\)</span></li>
<li class="fragment">Apply <strong>causal reasoning</strong> to cost-effectiveness analysis, avoiding naive cross-country comparisons</li>
<li class="fragment">Use R to simulate, visualize, and model data that exhibit these paradoxes</li>
<li class="fragment">Make sound <strong>resource-allocation recommendations</strong> for the Beginnings Fund’s $525M portfolio</li>
</ul>
</section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Book Context: Business Financials</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">From Slimtree Publishing to MNH cost-effectiveness</span></p>
</section>
<section class="slide level2">
<h2>The Slimtree Publishing Case</h2>
<div class="callout-box">
<p><strong>Chapter 6 of Ryall &amp; Bramson</strong> builds a causal model of a publishing company’s P&amp;L statement. Revenue and costs are decomposed into causal drivers, and the model is used to identify which financial levers have the greatest impact on profitability.</p>
</div>
<div class="fragment">
<p><strong>Key ideas from the book:</strong></p>
<ul>
<li class="fragment">A <strong>P&amp;L spreadsheet</strong> is already an implicit causal model – revenue minus costs equals profit</li>
<li class="fragment">Making the causal structure <strong>explicit</strong> reveals hidden assumptions (e.g., which costs are fixed vs.&nbsp;variable)</li>
<li class="fragment">Simpson’s Paradox arises when <strong>aggregated financial data</strong> masks segment-level effects</li>
<li class="fragment">The Prosecutor’s Fallacy leads to <strong>misinterpreting diagnostic signals</strong> about business health</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Transition: From Profit to Lives Saved</h2>
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>Slimtree Publishing</strong></p>
<ul>
<li>Objective: Maximize profit</li>
<li>Financial model: Revenue - Costs = Profit</li>
<li>Levers: Pricing, volume, cost structure</li>
<li>Paradox: A product line looks unprofitable overall but is profitable in every segment</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box green">
<p><strong>MNH Cost-Effectiveness</strong></p>
<ul>
<li>Objective: Maximize lives saved per dollar</li>
<li>Financial model: Cost / Lives Saved = CPLS</li>
<li>Levers: Intervention choice, country allocation, dosage</li>
<li>Paradox: An intervention looks ineffective overall but is effective in every country group</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>The same causal reasoning applies.</strong> Whether you are analyzing a publishing company’s profit margins or the Beginnings Fund’s cost-per-life-saved, Simpson’s Paradox and the Prosecutor’s Fallacy arise from the same structural features of the causal model.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Cost-Effectiveness in MNH</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Why naive country comparisons mislead</span></p>
</section>
<section class="slide level2">
<h2>The Key Metric: Cost Per Life Saved</h2>
<div class="definition-box">
<p><strong>Cost Per Life Saved (CPLS):</strong> The total program expenditure divided by the number of additional lives saved attributable to the intervention. Lower CPLS means greater efficiency.</p>
</div>
<div class="fragment">
<p><strong>Why CPLS matters for the Beginnings Fund:</strong></p>
<ul>
<li class="fragment">The Fund has <strong>$525 million</strong> to deploy across 10 countries</li>
<li class="fragment">Each country has different baseline mortality, health system capacity, and cost structures</li>
<li class="fragment">Naive comparisons of CPLS across countries can be <strong>deeply misleading</strong></li>
<li class="fragment">A country with high CPLS may actually be the <em>best</em> investment when you account for confounders</li>
</ul>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>The core problem:</strong> Comparing CPLS without adjusting for confounders (baseline severity, health system strength, population density) is like comparing apples to oranges – and can lead to catastrophically wrong allocation decisions.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Lives Saved Targets by Country</h2>
<p>The Beginnings Fund’s investment portfolio targets <strong>322,847 lives saved</strong> across 10 countries:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Country</th>
<th style="text-align: right;">Lives Saved Target</th>
<th style="text-align: right;">Share of Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ethiopia</td>
<td style="text-align: right;">86,124</td>
<td style="text-align: right;">26.7%</td>
</tr>
<tr class="even">
<td>Tanzania</td>
<td style="text-align: right;">63,497</td>
<td style="text-align: right;">19.7%</td>
</tr>
<tr class="odd">
<td>Kenya</td>
<td style="text-align: right;">46,494</td>
<td style="text-align: right;">14.4%</td>
</tr>
<tr class="even">
<td>Uganda</td>
<td style="text-align: right;">43,058</td>
<td style="text-align: right;">13.3%</td>
</tr>
<tr class="odd">
<td>Ghana</td>
<td style="text-align: right;">23,910</td>
<td style="text-align: right;">7.4%</td>
</tr>
<tr class="even">
<td>Malawi</td>
<td style="text-align: right;">20,761</td>
<td style="text-align: right;">6.4%</td>
</tr>
<tr class="odd">
<td>Zimbabwe</td>
<td style="text-align: right;">20,082</td>
<td style="text-align: right;">6.2%</td>
</tr>
<tr class="even">
<td>Rwanda</td>
<td style="text-align: right;">14,585</td>
<td style="text-align: right;">4.5%</td>
</tr>
<tr class="odd">
<td>Lesotho</td>
<td style="text-align: right;">4,336</td>
<td style="text-align: right;">1.3%</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>322,847</strong></td>
<td style="text-align: right;"><strong>100%</strong></td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout-box">
<p><strong>Note:</strong> Targets reflect both baseline mortality burden and projected intervention effectiveness. Ethiopia’s large share is driven by population size and high NMR, not simply by spending more.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>The Danger of Naive Rankings</h2>
<div class="columns-equal">
<div class="col">
<div class="example-block">
<p><span class="example-label">Naive Approach</span></p>
<p>Rank countries by raw CPLS:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Country</th>
<th style="text-align: right;">CPLS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rwanda</td>
<td style="text-align: right;">$820</td>
</tr>
<tr class="even">
<td>Malawi</td>
<td style="text-align: right;">$1,050</td>
</tr>
<tr class="odd">
<td>Ethiopia</td>
<td style="text-align: right;">$1,200</td>
</tr>
<tr class="even">
<td>Kenya</td>
<td style="text-align: right;">$1,450</td>
</tr>
<tr class="odd">
<td>Tanzania</td>
<td style="text-align: right;">$1,380</td>
</tr>
</tbody>
</table>
<p>“Invest everything in Rwanda – lowest CPLS!”</p>
</div>
</div>
<div class="col">
<div class="example-block">
<p><span class="example-label">Causal Approach</span></p>
<p>Adjust for baseline severity and health system strength:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Country</th>
<th style="text-align: right;">CPLS</th>
<th style="text-align: right;">Adjusted CPLS</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rwanda</td>
<td style="text-align: right;">$820</td>
<td style="text-align: right;">$1,340</td>
</tr>
<tr class="even">
<td>Malawi</td>
<td style="text-align: right;">$1,050</td>
<td style="text-align: right;">$1,180</td>
</tr>
<tr class="odd">
<td>Ethiopia</td>
<td style="text-align: right;">$1,200</td>
<td style="text-align: right;">$980</td>
</tr>
<tr class="even">
<td>Kenya</td>
<td style="text-align: right;">$1,450</td>
<td style="text-align: right;">$1,100</td>
</tr>
<tr class="odd">
<td>Tanzania</td>
<td style="text-align: right;">$1,380</td>
<td style="text-align: right;">$1,060</td>
</tr>
</tbody>
</table>
<p>“Ethiopia is actually most efficient!”</p>
</div>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>Rankings reverse</strong> when you condition on confounders. Rwanda’s low raw CPLS reflects its strong health system (low baseline severity), not superior intervention efficiency.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Simpson’s Paradox</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">When aggregated data reverses the truth</span></p>
</section>
<section class="slide level2">
<h2>Definition: Simpson’s Paradox</h2>
<div class="definition-box">
<p><strong>Simpson’s Paradox:</strong> A trend that appears in aggregated data <em>reverses</em> or disappears when the data is disaggregated by a confounding variable. The paradox arises when a lurking variable is associated with both the treatment and the outcome.</p>
</div>
<div class="fragment">
<p><strong>Why it matters:</strong></p>
<ul>
<li class="fragment">Decisions based on aggregated data can be <strong>exactly wrong</strong></li>
<li class="fragment">The paradox is not a statistical curiosity – it has led to real-world policy failures</li>
<li class="fragment">Resolution requires <strong>causal reasoning</strong>, not just statistical adjustment</li>
<li class="fragment">The key question: Should you condition on a variable, or not? The answer depends on the <strong>causal structure</strong>.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Classic Example: UC Berkeley Admissions</h2>
<div class="example-block">
<p><span class="example-label">The Famous Case (1973)</span></p>
<p>UC Berkeley was sued for gender bias in graduate admissions:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Applicants</th>
<th style="text-align: right;">Admitted</th>
<th style="text-align: right;">Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Men</strong></td>
<td style="text-align: right;">8,442</td>
<td style="text-align: right;">3,738</td>
<td style="text-align: right;"><strong>44%</strong></td>
</tr>
<tr class="even">
<td><strong>Women</strong></td>
<td style="text-align: right;">4,321</td>
<td style="text-align: right;">1,494</td>
<td style="text-align: right;"><strong>35%</strong></td>
</tr>
</tbody>
</table>
<p>Women appeared to be discriminated against overall.</p>
</div>
<div class="fragment">
<p><strong>But when broken down by department:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Department</th>
<th style="text-align: right;">Men Admit Rate</th>
<th style="text-align: right;">Women Admit Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td style="text-align: right;">62%</td>
<td style="text-align: right;"><strong>82%</strong></td>
</tr>
<tr class="even">
<td>B</td>
<td style="text-align: right;">63%</td>
<td style="text-align: right;"><strong>68%</strong></td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: right;">37%</td>
<td style="text-align: right;"><strong>34%</strong></td>
</tr>
<tr class="even">
<td>D</td>
<td style="text-align: right;">33%</td>
<td style="text-align: right;"><strong>35%</strong></td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>Within most departments, women were admitted at <em>higher</em> rates.</strong> The paradox arose because women applied disproportionately to competitive departments with low admission rates. <strong>Department choice</strong> was the confounder.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>MNH Example: CPAP Intervention</h2>
<p>Consider evaluating CPAP (Continuous Positive Airway Pressure) for neonatal respiratory distress across countries:</p>
<div class="example-block">
<p><span class="example-label">Aggregated Data</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">With CPAP</th>
<th style="text-align: right;">Without CPAP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Survival Rate</strong></td>
<td style="text-align: right;">72%</td>
<td style="text-align: right;">78%</td>
</tr>
</tbody>
</table>
<p>CPAP appears to <em>reduce</em> survival! Should we abandon it?</p>
</div>
<div class="fragment">
<div class="example-block">
<p><span class="example-label">Disaggregated by Country Group</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Country Group</th>
<th style="text-align: right;">With CPAP</th>
<th style="text-align: right;">Without CPAP</th>
<th style="text-align: right;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>High-burden</strong> (Ethiopia, Tanzania, Uganda)</td>
<td style="text-align: right;">68%</td>
<td style="text-align: right;">61%</td>
<td style="text-align: right;"><strong>+7 pp</strong></td>
</tr>
<tr class="even">
<td><strong>Low-burden</strong> (Rwanda, Kenya, Ghana)</td>
<td style="text-align: right;">85%</td>
<td style="text-align: right;">82%</td>
<td style="text-align: right;"><strong>+3 pp</strong></td>
</tr>
</tbody>
</table>
<p>CPAP <strong>improves</strong> survival in <em>every</em> group!</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>The Confounder: Baseline Severity</h2>
<p><strong>Why does this happen?</strong> The confounder is <strong>baseline severity</strong>:</p>
<ul>
<li class="fragment">High-burden countries have more severe cases (lower baseline survival)</li>
<li class="fragment">High-burden countries also use CPAP more frequently (greater need)</li>
<li class="fragment">The aggregated data mixes these two groups, and the <em>composition effect</em> overwhelms the <em>treatment effect</em></li>
</ul>
<div class="fragment">
<table style="width: 85%; margin: 0.4em auto; font-size: 0.55em;">
<tbody><tr>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node confounder">
Baseline<br>Severity
</div>
</td>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td style="text-align: center; padding: 0.3em;">
<span class="dag-arrow positive">↙ [+]</span>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.3em;">
<span class="dag-arrow negative">↘ [−]</span>
</td>
</tr>
<tr>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node treatment">
CPAP<br>Usage
</div>
</td>
<td style="text-align: center; padding: 0.3em;">
<span class="dag-arrow positive">→ [+]</span>
</td>
<td style="text-align: center; padding: 0.6em;">
<div class="dag-node outcome">
Survival<br>Rate
</div>
</td>
</tr>
</tbody></table>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>Baseline severity</strong> is a classic <em>fork</em> (diverging triplet): it causes both higher CPAP usage <em>and</em> lower survival. The spurious negative association between CPAP and survival is entirely driven by this confounder.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>The Numbers in Detail</h2>
<div class="columns-equal">
<div class="col">
<p><strong>Aggregated (misleading):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">CPAP</th>
<th style="text-align: right;">No CPAP</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survived</td>
<td style="text-align: right;">720</td>
<td style="text-align: right;">780</td>
<td style="text-align: right;">1,500</td>
</tr>
<tr class="even">
<td>Died</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">500</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>1,000</strong></td>
<td style="text-align: right;"><strong>1,000</strong></td>
<td style="text-align: right;">2,000</td>
</tr>
<tr class="even">
<td><strong>Rate</strong></td>
<td style="text-align: right;"><strong>72%</strong></td>
<td style="text-align: right;"><strong>78%</strong></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>CPAP looks worse: 72% vs 78%.</p>
</div>
<div class="col">
<p><strong>Disaggregated (correct):</strong></p>
<p><em>High-burden (n = 1,400):</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">CPAP</th>
<th style="text-align: right;">No CPAP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survived</td>
<td style="text-align: right;">544</td>
<td style="text-align: right;">183</td>
</tr>
<tr class="even">
<td>Total</td>
<td style="text-align: right;">800</td>
<td style="text-align: right;">300</td>
</tr>
<tr class="odd">
<td><strong>Rate</strong></td>
<td style="text-align: right;"><strong>68%</strong></td>
<td style="text-align: right;"><strong>61%</strong></td>
</tr>
</tbody>
</table>
<p><em>Low-burden (n = 600):</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">CPAP</th>
<th style="text-align: right;">No CPAP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Survived</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">574</td>
</tr>
<tr class="even">
<td>Total</td>
<td style="text-align: right;">200</td>
<td style="text-align: right;">700</td>
</tr>
<tr class="odd">
<td><strong>Rate</strong></td>
<td style="text-align: right;"><strong>85%</strong></td>
<td style="text-align: right;"><strong>82%</strong></td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>The composition effect:</strong> 80% of CPAP cases come from high-burden countries (where baseline survival is lower), but only 30% of non-CPAP cases do. The groups are not comparable without stratification.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>The DAG That Generates Simpson’s Paradox</h2>
<div class="definition-box">
<p><strong>Simpson’s Paradox arises whenever a confounder creates a fork structure:</strong> a variable that is a common cause of both the treatment assignment and the outcome.</p>
</div>
<div class="fragment">
<table style="width: 90%; margin: 0.4em auto; font-size: 0.5em;">
<tbody><tr>
<td colspan="5" style="text-align: center; padding: 0.5em;">
<div class="dag-node confounder">
Confounder<br>(Baseline Severity / Country Group)
</div>
</td>
</tr>
<tr>
<td style="text-align: center; padding: 0.3em;">
<span class="dag-arrow">↓</span>
</td>
<td>
</td>
<td>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.3em;">
<span class="dag-arrow">↓</span>
</td>
</tr>
<tr>
<td style="text-align: center; padding: 0.5em;">
<div class="dag-node treatment">
Treatment<br>(CPAP Usage)
</div>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.5em;">
<span class="dag-arrow positive">→ [+]</span>
</td>
<td>
</td>
<td style="text-align: center; padding: 0.5em;">
<div class="dag-node outcome">
Outcome<br>(Survival Rate)
</div>
</td>
</tr>
</tbody></table>
</div>
<div class="fragment">
<p><strong>Resolution:</strong> Condition on (stratify by) the confounder. The <strong>stratified</strong> estimates give the correct causal effect.</p>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>Critical rule:</strong> Always condition on <strong>confounders</strong> (common causes of treatment and outcome). Never condition on <strong>mediators</strong> (variables on the causal path between treatment and outcome). Conditioning on a mediator <em>blocks</em> the causal effect you are trying to estimate.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Key Insight: Confounders vs.&nbsp;Mediators</h2>
<div class="columns-equal">
<div class="col">
<div class="callout-box green">
<p><strong>Condition on CONFOUNDERS</strong></p>
<p>Confounder is a common cause:</p>
<p>Treatment <span class="math inline">\(\leftarrow\)</span> Confounder <span class="math inline">\(\rightarrow\)</span> Outcome</p>
<p>Conditioning <em>removes</em> the spurious association and reveals the true causal effect.</p>
<p><span class="good-example">Always stratify by confounders</span></p>
</div>
</div>
<div class="col">
<div class="callout-box red">
<p><strong>Do NOT condition on MEDIATORS</strong></p>
<p>Mediator is on the causal path:</p>
<p>Treatment <span class="math inline">\(\rightarrow\)</span> Mediator <span class="math inline">\(\rightarrow\)</span> Outcome</p>
<p>Conditioning <em>blocks</em> the very causal pathway you want to measure.</p>
<p><span class="bad-example">Never stratify by mediators</span></p>
</div>
</div>
</div>
<div class="fragment">
<div class="example-block">
<p><span class="example-label">MNH Example</span></p>
<ul>
<li><strong>Confounder:</strong> Baseline severity (condition on it – YES)</li>
<li><strong>Mediator:</strong> Quality of care improvement (do NOT condition on it – blocking the effect of investment on mortality)</li>
<li>Getting this wrong leads to Simpson’s Paradox or underestimation of treatment effects</li>
</ul>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>The Prosecutor’s Fallacy</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Confusing the direction of conditional probability</span></p>
</section>
<section class="slide level2">
<h2>Definition: The Prosecutor’s Fallacy</h2>
<div class="definition-box">
<p><strong>The Prosecutor’s Fallacy:</strong> Confusing <span class="math inline">\(P(\text{Evidence} \mid \text{Hypothesis})\)</span> with <span class="math inline">\(P(\text{Hypothesis} \mid \text{Evidence})\)</span>. That is, mistaking the probability of observing the evidence <em>given</em> that a hypothesis is true for the probability that the hypothesis is true <em>given</em> the evidence.</p>
</div>
<div class="fragment">
<p><strong>The classic courtroom version:</strong></p>
<ul>
<li class="fragment">A DNA match occurs in 1 in 1,000,000 people</li>
<li class="fragment">Prosecutor argues: “There is only a 1-in-a-million chance the defendant is innocent!”</li>
<li class="fragment">But in a city of 5 million people, <strong>5 people</strong> match the DNA</li>
<li class="fragment"><span class="math inline">\(P(\text{match} \mid \text{innocent}) = 0.0001\%\)</span> but <span class="math inline">\(P(\text{innocent} \mid \text{match})\)</span> could be <span class="math inline">\(\frac{4}{5} = 80\%\)</span></li>
</ul>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>The fallacy:</strong> The probability of the evidence given innocence is NOT the probability of innocence given the evidence. You need Bayes’ rule and the <strong>base rate</strong> to convert one into the other.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>MNH Example: Preeclampsia Screening</h2>
<div class="example-block">
<p><span class="example-label">The Diagnostic Test</span></p>
<p>A screening test for <strong>preeclampsia</strong> in pregnant women has the following performance:</p>
<ul>
<li><strong>Sensitivity:</strong> 90% – <span class="math inline">\(P(\text{positive test} \mid \text{has preeclampsia}) = 0.90\)</span></li>
<li><strong>Specificity:</strong> 85% – <span class="math inline">\(P(\text{negative test} \mid \text{no preeclampsia}) = 0.85\)</span></li>
<li><strong>Prevalence:</strong> 5% – <span class="math inline">\(P(\text{preeclampsia}) = 0.05\)</span></li>
</ul>
</div>
<div class="fragment">
<p><strong>The Prosecutor’s Fallacy in action:</strong></p>
<p>A health worker sees a positive test result and tells the patient: <em>“The test is 90% accurate, so there is a 90% chance you have preeclampsia.”</em></p>
</div>
<div class="fragment">
<div class="callout-box red">
<p><strong>This is WRONG.</strong> The 90% is <span class="math inline">\(P(\text{positive} \mid \text{disease})\)</span>, not <span class="math inline">\(P(\text{disease} \mid \text{positive})\)</span>. To find the latter, we need <strong>Bayes’ rule</strong>.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Bayes’ Rule Calculation</h2>
<div class="math-block">
<p><span class="math display">\[P(\text{disease} \mid \text{positive}) = \frac{P(\text{positive} \mid \text{disease}) \times P(\text{disease})}{P(\text{positive})}\]</span></p>
</div>
<div class="fragment">
<p><strong>Step 1: Compute <span class="math inline">\(P(\text{positive})\)</span> using the law of total probability:</strong></p>
<div class="math-block">
<p><span class="math display">\[P(\text{positive}) = P(\text{pos} \mid \text{disease}) \times P(\text{disease}) + P(\text{pos} \mid \text{no disease}) \times P(\text{no disease})\]</span> <span class="math display">\[= (0.90)(0.05) + (0.15)(0.95) = 0.045 + 0.1425 = 0.1875\]</span></p>
</div>
</div>
<div class="fragment">
<p><strong>Step 2: Apply Bayes’ rule:</strong></p>
<div class="math-block">
<p><span class="math display">\[P(\text{disease} \mid \text{positive}) = \frac{(0.90)(0.05)}{0.1875} = \frac{0.045}{0.1875} \approx 0.24\]</span></p>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>A positive test means only a 24% chance of preeclampsia</strong> – not 90%! The low base rate (5% prevalence) means most positive tests are <strong>false positives</strong>.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Visualizing the Fallacy</h2>
<p>Consider 10,000 pregnant women screened:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">Has Preeclampsia (500)</th>
<th style="text-align: right;">No Preeclampsia (9,500)</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Test Positive</strong></td>
<td style="text-align: right;">450 (true pos)</td>
<td style="text-align: right;">1,425 (false pos)</td>
<td style="text-align: right;"><strong>1,875</strong></td>
</tr>
<tr class="even">
<td><strong>Test Negative</strong></td>
<td style="text-align: right;">50 (false neg)</td>
<td style="text-align: right;">8,075 (true neg)</td>
<td style="text-align: right;">8,125</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>Of the <strong>1,875 positive tests</strong>, only <strong>450</strong> (24%) actually have preeclampsia.</p>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>The DAG for correct inference:</strong></p>
<p>The key insight is that <strong>prevalence</strong> (base rate) is a prior that must be combined with the likelihood (test accuracy) to produce the posterior (probability of disease given positive test). Ignoring the base rate is the essence of the Prosecutor’s Fallacy.</p>
</div>
</div>
<div class="fragment">
<table style="width: 75%; margin: 0.3em auto; font-size: 0.5em;">
<tbody><tr>
<td style="text-align: center; padding: 0.5em;">
<div class="dag-node confounder">
Prevalence<br>(Base Rate)
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow positive">→ [+]</span>
</td>
<td style="text-align: center; padding: 0.5em;">
<div class="dag-node">
Disease<br>Status
</div>
</td>
<td style="text-align: center;">
<span class="dag-arrow positive">→ [+]</span>
</td>
<td style="text-align: center; padding: 0.5em;">
<div class="dag-node outcome">
Test<br>Result
</div>
</td>
</tr>
</tbody></table>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>MNH Application: Cross-Country Cost-Effectiveness</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Applying causal reasoning to the $525M allocation</span></p>
</section>
<section class="slide level2">
<h2>Cost-Effectiveness Data Across Countries</h2>
<p>Estimated cost per life saved (CPLS) for three key interventions:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Country</th>
<th style="text-align: right;">CPAP</th>
<th style="text-align: right;">PPH Bundle</th>
<th style="text-align: right;">Workforce Training</th>
<th style="text-align: right;">Baseline NMR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ethiopia</td>
<td style="text-align: right;">$1,250</td>
<td style="text-align: right;">$890</td>
<td style="text-align: right;">$1,650</td>
<td style="text-align: right;">29/1,000</td>
</tr>
<tr class="even">
<td>Tanzania</td>
<td style="text-align: right;">$1,180</td>
<td style="text-align: right;">$950</td>
<td style="text-align: right;">$1,520</td>
<td style="text-align: right;">25/1,000</td>
</tr>
<tr class="odd">
<td>Kenya</td>
<td style="text-align: right;">$1,450</td>
<td style="text-align: right;">$1,100</td>
<td style="text-align: right;">$1,380</td>
<td style="text-align: right;">21/1,000</td>
</tr>
<tr class="even">
<td>Uganda</td>
<td style="text-align: right;">$1,300</td>
<td style="text-align: right;">$870</td>
<td style="text-align: right;">$1,700</td>
<td style="text-align: right;">27/1,000</td>
</tr>
<tr class="odd">
<td>Ghana</td>
<td style="text-align: right;">$1,550</td>
<td style="text-align: right;">$1,200</td>
<td style="text-align: right;">$1,250</td>
<td style="text-align: right;">18/1,000</td>
</tr>
<tr class="even">
<td>Rwanda</td>
<td style="text-align: right;">$820</td>
<td style="text-align: right;">$680</td>
<td style="text-align: right;">$980</td>
<td style="text-align: right;">17/1,000</td>
</tr>
<tr class="odd">
<td>Malawi</td>
<td style="text-align: right;">$1,050</td>
<td style="text-align: right;">$780</td>
<td style="text-align: right;">$1,400</td>
<td style="text-align: right;">26/1,000</td>
</tr>
<tr class="even">
<td>Zimbabwe</td>
<td style="text-align: right;">$1,100</td>
<td style="text-align: right;">$850</td>
<td style="text-align: right;">$1,150</td>
<td style="text-align: right;">23/1,000</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout-box orange">
<p><strong>Tempting but wrong:</strong> Simply pick the country-intervention pair with the lowest CPLS (Rwanda, PPH bundle at $680). But Rwanda’s low CPLS reflects its strong health system, not necessarily a larger <em>causal</em> impact of the intervention.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Naive Ranking vs.&nbsp;Causal Ranking</h2>
<div class="columns-equal">
<div class="col">
<div class="callout-box red">
<p><strong>Naive Ranking (by raw CPLS)</strong></p>
<ol type="1">
<li>Rwanda – PPH ($680)</li>
<li>Malawi – PPH ($780)</li>
<li>Rwanda – CPAP ($820)</li>
<li>Zimbabwe – PPH ($850)</li>
<li>Uganda – PPH ($870)</li>
</ol>
<p><em>Concentrates investment in countries with strong health systems and low mortality burden.</em></p>
</div>
</div>
<div class="col">
<div class="callout-box green">
<p><strong>Causal Ranking (adjusted for confounders)</strong></p>
<ol type="1">
<li>Ethiopia – PPH ($890 raw, high marginal impact)</li>
<li>Uganda – PPH ($870 raw, large unmet need)</li>
<li>Tanzania – PPH ($950 raw, high burden)</li>
<li>Malawi – CPAP ($1,050, weak systems amplify effect)</li>
<li>Ethiopia – CPAP ($1,250, massive population)</li>
</ol>
<p><em>Targets countries where the </em>causal effect* of intervention is greatest.*</p>
</div>
</div>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>The confounders that drive the difference:</strong> Baseline NMR (severity), health system capacity, population size, and existing intervention coverage. Adjusting for these reveals where each additional dollar has the greatest <em>marginal</em> impact on lives saved.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Simpson’s Paradox in Cost-Effectiveness</h2>
<p>Consider a PPH bundle intervention evaluated across all 10 countries:</p>
<div class="columns-equal">
<div class="col">
<div class="example-block">
<p><span class="example-label">Aggregated</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">PPH Bundle</th>
<th style="text-align: right;">Standard Care</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mortality Rate</td>
<td style="text-align: right;">3.2%</td>
<td style="text-align: right;">2.8%</td>
</tr>
</tbody>
</table>
<p>PPH bundle appears <strong>worse</strong> than standard care!</p>
</div>
</div>
<div class="col">
<div class="example-block">
<p><span class="example-label">Stratified by Health System Strength</span></p>
<p><em>Weak systems (Ethiopia, Uganda, Malawi, Tanzania):</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">PPH Bundle</th>
<th style="text-align: right;">Standard Care</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mortality</td>
<td style="text-align: right;">4.1%</td>
<td style="text-align: right;">5.8%</td>
</tr>
</tbody>
</table>
<p><em>Strong systems (Rwanda, Kenya, Ghana, Zimbabwe):</em></p>
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;">PPH Bundle</th>
<th style="text-align: right;">Standard Care</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mortality</td>
<td style="text-align: right;">1.5%</td>
<td style="text-align: right;">1.9%</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>The PPH bundle reduces mortality in BOTH strata.</strong> The aggregated data is misleading because the bundle is deployed disproportionately in weak-system countries (where baseline mortality is higher). Health system strength is the confounder.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Policy Implication: The Next $50M</h2>
<div class="callout-box">
<p><strong>Decision:</strong> The Beginnings Fund has an additional $50M to allocate. Where should it go?</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box red">
<p><strong>Without causal reasoning:</strong></p>
<ul>
<li>Allocate to Rwanda and Ghana (lowest raw CPLS)</li>
<li>Expected lives saved: ~8,200</li>
<li>Ignores diminishing returns in strong systems</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box green">
<p><strong>With causal reasoning:</strong></p>
<ul>
<li>Allocate to Ethiopia and Tanzania (highest marginal impact after confounder adjustment)</li>
<li>Expected lives saved: ~14,600</li>
<li>Accounts for unmet need, baseline severity, and system capacity</li>
</ul>
</div>
</div>
</div>
</div>
<div class="fragment">
<p><strong>The causal approach saves an additional 6,400 lives with the same budget.</strong></p>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>This is not hypothetical.</strong> Misallocation of global health funds due to Simpson’s Paradox-style reasoning has been documented in HIV/AIDS, malaria, and vaccination programs. Causal thinking is not academic – it is life-or-death.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Interactive Exercise</h2>
<div class="callout-box">
<p><strong>Your turn:</strong> Work in small groups (5 minutes).</p>
</div>
<div class="fragment">
<p><strong>Scenario:</strong> You are advising the Beginnings Fund. The data shows:</p>
<ul>
<li><strong>Workforce training</strong> has a CPLS of $1,650 in Ethiopia but only $980 in Rwanda</li>
<li>Ethiopia has a staff:patient ratio of 1:22; Rwanda has 1:6</li>
<li>Ethiopia’s baseline NMR is 29/1,000; Rwanda’s is 17/1,000</li>
</ul>
</div>
<div class="fragment">
<p><strong>Questions:</strong></p>
<ol type="1">
<li class="fragment">Is workforce training more cost-effective in Rwanda or Ethiopia <em>at the margin</em>?</li>
<li class="fragment">What is the confounder driving the raw CPLS difference?</li>
<li class="fragment">Draw the DAG showing the relationship between health system capacity, CPLS, and lives saved.</li>
<li class="fragment">Where would you invest the next $10M in workforce training? Justify with causal reasoning.</li>
</ol>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>R Code Workshop</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Simulating and analyzing Simpson’s Paradox and the Prosecutor’s Fallacy</span></p>
</section>
<section class="slide level2">
<h2>R Block 1: Simulating Simpson’s Paradox</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href=""></a></span>
<span id="cb1-3"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-4"><a href=""></a></span>
<span id="cb1-5"><a href=""></a><span class="co"># Simulate MNH data exhibiting Simpson's Paradox</span></span>
<span id="cb1-6"><a href=""></a><span class="co"># Confounder: country_group (high-burden vs low-burden)</span></span>
<span id="cb1-7"><a href=""></a>n <span class="ot">&lt;-</span> <span class="dv">2000</span></span>
<span id="cb1-8"><a href=""></a></span>
<span id="cb1-9"><a href=""></a>mnh_data <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-10"><a href=""></a>  <span class="co"># Confounder: country group determines both treatment and baseline risk</span></span>
<span id="cb1-11"><a href=""></a> <span class="at">country_group =</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">"High-burden"</span>, <span class="st">"Low-burden"</span>), n, <span class="at">replace =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-12"><a href=""></a>                         <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.6</span>, <span class="fl">0.4</span>)),</span>
<span id="cb1-13"><a href=""></a>  <span class="co"># Treatment assignment depends on country group (confounder)</span></span>
<span id="cb1-14"><a href=""></a>  <span class="at">cpap =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-15"><a href=""></a>    country_group <span class="sc">==</span> <span class="st">"High-burden"</span> <span class="sc">~</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.75</span>),</span>
<span id="cb1-16"><a href=""></a>    country_group <span class="sc">==</span> <span class="st">"Low-burden"</span>  <span class="sc">~</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, <span class="fl">0.25</span>)</span>
<span id="cb1-17"><a href=""></a>  ),</span>
<span id="cb1-18"><a href=""></a>  <span class="co"># Outcome depends on BOTH country group and treatment</span></span>
<span id="cb1-19"><a href=""></a>  <span class="co"># CPAP has a positive causal effect (+10pp), but high-burden has lower baseline</span></span>
<span id="cb1-20"><a href=""></a>  <span class="at">survival_prob =</span> <span class="fu">case_when</span>(</span>
<span id="cb1-21"><a href=""></a>    country_group <span class="sc">==</span> <span class="st">"High-burden"</span> <span class="sc">&amp;</span> cpap <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="fl">0.68</span>,</span>
<span id="cb1-22"><a href=""></a>    country_group <span class="sc">==</span> <span class="st">"High-burden"</span> <span class="sc">&amp;</span> cpap <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="fl">0.61</span>,</span>
<span id="cb1-23"><a href=""></a>    country_group <span class="sc">==</span> <span class="st">"Low-burden"</span>  <span class="sc">&amp;</span> cpap <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="fl">0.85</span>,</span>
<span id="cb1-24"><a href=""></a>    country_group <span class="sc">==</span> <span class="st">"Low-burden"</span>  <span class="sc">&amp;</span> cpap <span class="sc">==</span> <span class="dv">0</span> <span class="sc">~</span> <span class="fl">0.82</span></span>
<span id="cb1-25"><a href=""></a>  ),</span>
<span id="cb1-26"><a href=""></a>  <span class="at">survived =</span> <span class="fu">rbinom</span>(n, <span class="dv">1</span>, survival_prob)</span>
<span id="cb1-27"><a href=""></a>)</span>
<span id="cb1-28"><a href=""></a></span>
<span id="cb1-29"><a href=""></a><span class="co"># Aggregated result (misleading)</span></span>
<span id="cb1-30"><a href=""></a>mnh_data <span class="sc">|&gt;</span></span>
<span id="cb1-31"><a href=""></a>  <span class="fu">group_by</span>(cpap) <span class="sc">|&gt;</span></span>
<span id="cb1-32"><a href=""></a>  <span class="fu">summarise</span>(<span class="at">survival_rate =</span> <span class="fu">mean</span>(survived), <span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span>
<span id="cb1-33"><a href=""></a></span>
<span id="cb1-34"><a href=""></a><span class="co"># Disaggregated result (correct)</span></span>
<span id="cb1-35"><a href=""></a>mnh_data <span class="sc">|&gt;</span></span>
<span id="cb1-36"><a href=""></a>  <span class="fu">group_by</span>(country_group, cpap) <span class="sc">|&gt;</span></span>
<span id="cb1-37"><a href=""></a>  <span class="fu">summarise</span>(<span class="at">survival_rate =</span> <span class="fu">mean</span>(survived), <span class="at">n =</span> <span class="fu">n</span>(), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 2: Visualizing Aggregated vs.&nbsp;Stratified</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb2-2"><a href=""></a></span>
<span id="cb2-3"><a href=""></a><span class="co"># Prepare labels</span></span>
<span id="cb2-4"><a href=""></a>mnh_data <span class="ot">&lt;-</span> mnh_data <span class="sc">|&gt;</span></span>
<span id="cb2-5"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">cpap_label =</span> <span class="fu">ifelse</span>(cpap <span class="sc">==</span> <span class="dv">1</span>, <span class="st">"CPAP"</span>, <span class="st">"No CPAP"</span>))</span>
<span id="cb2-6"><a href=""></a></span>
<span id="cb2-7"><a href=""></a><span class="co"># Aggregated view (misleading)</span></span>
<span id="cb2-8"><a href=""></a>p_agg <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mnh_data, <span class="fu">aes</span>(<span class="at">x =</span> cpap_label, <span class="at">y =</span> survived, <span class="at">fill =</span> cpap_label)) <span class="sc">+</span></span>
<span id="cb2-9"><a href=""></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb2-10"><a href=""></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb2-11"><a href=""></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"CPAP"</span> <span class="ot">=</span> <span class="st">"#005CB9"</span>, <span class="st">"No CPAP"</span> <span class="ot">=</span> <span class="st">"#FA7650"</span>)) <span class="sc">+</span></span>
<span id="cb2-12"><a href=""></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb2-13"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Aggregated: CPAP Looks Harmful"</span>,</span>
<span id="cb2-14"><a href=""></a>       <span class="at">y =</span> <span class="st">"Survival Rate"</span>, <span class="at">x =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb2-15"><a href=""></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb2-16"><a href=""></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb2-17"><a href=""></a></span>
<span id="cb2-18"><a href=""></a><span class="co"># Stratified view (correct)</span></span>
<span id="cb2-19"><a href=""></a>p_strat <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(mnh_data, <span class="fu">aes</span>(<span class="at">x =</span> cpap_label, <span class="at">y =</span> survived, <span class="at">fill =</span> cpap_label)) <span class="sc">+</span></span>
<span id="cb2-20"><a href=""></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">"bar"</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb2-21"><a href=""></a>  <span class="fu">stat_summary</span>(<span class="at">fun.data =</span> mean_cl_boot, <span class="at">geom =</span> <span class="st">"errorbar"</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb2-22"><a href=""></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> country_group) <span class="sc">+</span></span>
<span id="cb2-23"><a href=""></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"CPAP"</span> <span class="ot">=</span> <span class="st">"#005CB9"</span>, <span class="st">"No CPAP"</span> <span class="ot">=</span> <span class="st">"#FA7650"</span>)) <span class="sc">+</span></span>
<span id="cb2-24"><a href=""></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span>percent, <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb2-25"><a href=""></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Stratified: CPAP Helps in BOTH Groups"</span>,</span>
<span id="cb2-26"><a href=""></a>       <span class="at">y =</span> <span class="st">"Survival Rate"</span>, <span class="at">x =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb2-27"><a href=""></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb2-28"><a href=""></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span>
<span id="cb2-29"><a href=""></a></span>
<span id="cb2-30"><a href=""></a><span class="fu">library</span>(patchwork)</span>
<span id="cb2-31"><a href=""></a>p_agg <span class="sc">+</span> p_strat <span class="sc">+</span></span>
<span id="cb2-32"><a href=""></a>  <span class="fu">plot_annotation</span>(<span class="at">title =</span> <span class="st">"Simpson's Paradox in MNH Data"</span>,</span>
<span id="cb2-33"><a href=""></a>                  <span class="at">subtitle =</span> <span class="st">"Same data, opposite conclusions"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 3: Naive vs.&nbsp;Confounder-Adjusted Regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="co"># Naive regression: ignores confounder</span></span>
<span id="cb3-2"><a href=""></a>naive_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(survived <span class="sc">~</span> cpap, <span class="at">data =</span> mnh_data)</span>
<span id="cb3-3"><a href=""></a><span class="fu">summary</span>(naive_model)</span>
<span id="cb3-4"><a href=""></a><span class="co"># Expected: CPAP coefficient is NEGATIVE (misleading)</span></span>
<span id="cb3-5"><a href=""></a></span>
<span id="cb3-6"><a href=""></a><span class="co"># Confounder-adjusted regression: includes country_group</span></span>
<span id="cb3-7"><a href=""></a>adjusted_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(survived <span class="sc">~</span> cpap <span class="sc">+</span> country_group, <span class="at">data =</span> mnh_data)</span>
<span id="cb3-8"><a href=""></a><span class="fu">summary</span>(adjusted_model)</span>
<span id="cb3-9"><a href=""></a><span class="co"># Expected: CPAP coefficient is POSITIVE (correct)</span></span>
<span id="cb3-10"><a href=""></a></span>
<span id="cb3-11"><a href=""></a><span class="co"># Compare coefficients side by side</span></span>
<span id="cb3-12"><a href=""></a><span class="fu">tibble</span>(</span>
<span id="cb3-13"><a href=""></a>  <span class="at">Model =</span> <span class="fu">c</span>(<span class="st">"Naive (no confounder)"</span>, <span class="st">"Adjusted (with confounder)"</span>),</span>
<span id="cb3-14"><a href=""></a>  <span class="at">CPAP_Coefficient =</span> <span class="fu">c</span>(<span class="fu">coef</span>(naive_model)[<span class="st">"cpap"</span>],</span>
<span id="cb3-15"><a href=""></a>                       <span class="fu">coef</span>(adjusted_model)[<span class="st">"cpap"</span>]),</span>
<span id="cb3-16"><a href=""></a>  <span class="at">Interpretation =</span> <span class="fu">c</span>(<span class="st">"CPAP appears harmful"</span>,</span>
<span id="cb3-17"><a href=""></a>                     <span class="st">"CPAP is beneficial (+7pp)"</span>)</span>
<span id="cb3-18"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>Key lesson:</strong> The naive model estimates a <em>negative</em> effect of CPAP on survival. The adjusted model, which conditions on the confounder (country group), correctly estimates a <em>positive</em> effect. <strong>Omitted variable bias</strong> is the statistical signature of Simpson’s Paradox.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>R Block 4: Bayesian Network with bnlearn</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">library</span>(bnlearn)</span>
<span id="cb4-2"><a href=""></a></span>
<span id="cb4-3"><a href=""></a><span class="co"># Prepare data for bnlearn (factors required)</span></span>
<span id="cb4-4"><a href=""></a>bn_data <span class="ot">&lt;-</span> mnh_data <span class="sc">|&gt;</span></span>
<span id="cb4-5"><a href=""></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-6"><a href=""></a>    <span class="at">country_group =</span> <span class="fu">factor</span>(country_group),</span>
<span id="cb4-7"><a href=""></a>    <span class="at">cpap =</span> <span class="fu">factor</span>(cpap, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No"</span>, <span class="st">"Yes"</span>)),</span>
<span id="cb4-8"><a href=""></a>    <span class="at">survived =</span> <span class="fu">factor</span>(survived, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Died"</span>, <span class="st">"Survived"</span>))</span>
<span id="cb4-9"><a href=""></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb4-10"><a href=""></a>  <span class="fu">select</span>(country_group, cpap, survived) <span class="sc">|&gt;</span></span>
<span id="cb4-11"><a href=""></a>  <span class="fu">as.data.frame</span>()</span>
<span id="cb4-12"><a href=""></a></span>
<span id="cb4-13"><a href=""></a><span class="co"># Define the causal structure (DAG)</span></span>
<span id="cb4-14"><a href=""></a>dag <span class="ot">&lt;-</span> <span class="fu">model2network</span>(<span class="st">"[country_group][cpap|country_group][survived|cpap:country_group]"</span>)</span>
<span id="cb4-15"><a href=""></a><span class="fu">plot</span>(dag)</span>
<span id="cb4-16"><a href=""></a></span>
<span id="cb4-17"><a href=""></a><span class="co"># Fit the BN with maximum likelihood estimates</span></span>
<span id="cb4-18"><a href=""></a>fitted_bn <span class="ot">&lt;-</span> <span class="fu">bn.fit</span>(dag, bn_data)</span>
<span id="cb4-19"><a href=""></a></span>
<span id="cb4-20"><a href=""></a><span class="co"># Query: P(survived | do(cpap = Yes)) using causal reasoning</span></span>
<span id="cb4-21"><a href=""></a><span class="co"># Marginalizing over country_group (the back-door adjustment)</span></span>
<span id="cb4-22"><a href=""></a><span class="fu">cpquery</span>(fitted_bn,</span>
<span id="cb4-23"><a href=""></a>        <span class="at">event =</span> (survived <span class="sc">==</span> <span class="st">"Survived"</span>),</span>
<span id="cb4-24"><a href=""></a>        <span class="at">evidence =</span> (cpap <span class="sc">==</span> <span class="st">"Yes"</span>),</span>
<span id="cb4-25"><a href=""></a>        <span class="at">n =</span> <span class="dv">100000</span>)</span>
<span id="cb4-26"><a href=""></a></span>
<span id="cb4-27"><a href=""></a><span class="co"># Compare: P(survived | cpap = Yes, country_group = High-burden)</span></span>
<span id="cb4-28"><a href=""></a><span class="fu">cpquery</span>(fitted_bn,</span>
<span id="cb4-29"><a href=""></a>        <span class="at">event =</span> (survived <span class="sc">==</span> <span class="st">"Survived"</span>),</span>
<span id="cb4-30"><a href=""></a>        <span class="at">evidence =</span> (cpap <span class="sc">==</span> <span class="st">"Yes"</span> <span class="sc">&amp;</span> country_group <span class="sc">==</span> <span class="st">"High-burden"</span>),</span>
<span id="cb4-31"><a href=""></a>        <span class="at">n =</span> <span class="dv">100000</span>)</span>
<span id="cb4-32"><a href=""></a></span>
<span id="cb4-33"><a href=""></a><span class="co"># The BN correctly handles the conditioning automatically</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>The Bayesian network encodes the causal structure.</strong> Queries on the fitted BN respect the DAG and give correct causal estimates, avoiding Simpson’s Paradox by construction.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>R Block 5: Prosecutor’s Fallacy Calculator</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="co"># Bayes' rule calculator for diagnostic tests</span></span>
<span id="cb5-2"><a href=""></a>bayes_diagnostic <span class="ot">&lt;-</span> <span class="cf">function</span>(sensitivity, specificity, prevalence) {</span>
<span id="cb5-3"><a href=""></a>  <span class="co"># P(positive | disease) = sensitivity</span></span>
<span id="cb5-4"><a href=""></a>  <span class="co"># P(negative | no disease) = specificity</span></span>
<span id="cb5-5"><a href=""></a>  <span class="co"># P(positive | no disease) = 1 - specificity (false positive rate)</span></span>
<span id="cb5-6"><a href=""></a>  <span class="co"># P(disease) = prevalence</span></span>
<span id="cb5-7"><a href=""></a></span>
<span id="cb5-8"><a href=""></a>  p_pos_given_disease    <span class="ot">&lt;-</span> sensitivity</span>
<span id="cb5-9"><a href=""></a>  p_pos_given_no_disease <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> specificity</span>
<span id="cb5-10"><a href=""></a>  p_disease              <span class="ot">&lt;-</span> prevalence</span>
<span id="cb5-11"><a href=""></a>  p_no_disease           <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> prevalence</span>
<span id="cb5-12"><a href=""></a></span>
<span id="cb5-13"><a href=""></a>  <span class="co"># Total probability of a positive test</span></span>
<span id="cb5-14"><a href=""></a>  p_positive <span class="ot">&lt;-</span> (p_pos_given_disease <span class="sc">*</span> p_disease) <span class="sc">+</span></span>
<span id="cb5-15"><a href=""></a>                (p_pos_given_no_disease <span class="sc">*</span> p_no_disease)</span>
<span id="cb5-16"><a href=""></a></span>
<span id="cb5-17"><a href=""></a>  <span class="co"># Bayes' rule: P(disease | positive)</span></span>
<span id="cb5-18"><a href=""></a>  p_disease_given_pos <span class="ot">&lt;-</span> (p_pos_given_disease <span class="sc">*</span> p_disease) <span class="sc">/</span> p_positive</span>
<span id="cb5-19"><a href=""></a></span>
<span id="cb5-20"><a href=""></a>  <span class="co"># Return results</span></span>
<span id="cb5-21"><a href=""></a>  <span class="fu">tibble</span>(</span>
<span id="cb5-22"><a href=""></a>    <span class="at">Metric =</span> <span class="fu">c</span>(<span class="st">"Sensitivity"</span>, <span class="st">"Specificity"</span>, <span class="st">"Prevalence"</span>,</span>
<span id="cb5-23"><a href=""></a>               <span class="st">"P(Positive Test)"</span>, <span class="st">"P(Disease | Positive) [PPV]"</span>,</span>
<span id="cb5-24"><a href=""></a>               <span class="st">"Prosecutor's Fallacy Would Claim"</span>),</span>
<span id="cb5-25"><a href=""></a>    <span class="at">Value =</span> <span class="fu">c</span>(</span>
<span id="cb5-26"><a href=""></a>      scales<span class="sc">::</span><span class="fu">percent</span>(sensitivity, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="cb5-27"><a href=""></a>      scales<span class="sc">::</span><span class="fu">percent</span>(specificity, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="cb5-28"><a href=""></a>      scales<span class="sc">::</span><span class="fu">percent</span>(prevalence, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="cb5-29"><a href=""></a>      scales<span class="sc">::</span><span class="fu">percent</span>(p_positive, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="cb5-30"><a href=""></a>      scales<span class="sc">::</span><span class="fu">percent</span>(p_disease_given_pos, <span class="at">accuracy =</span> <span class="fl">0.1</span>),</span>
<span id="cb5-31"><a href=""></a>      scales<span class="sc">::</span><span class="fu">percent</span>(sensitivity, <span class="at">accuracy =</span> <span class="fl">0.1</span>)</span>
<span id="cb5-32"><a href=""></a>    )</span>
<span id="cb5-33"><a href=""></a>  )</span>
<span id="cb5-34"><a href=""></a>}</span>
<span id="cb5-35"><a href=""></a></span>
<span id="cb5-36"><a href=""></a><span class="co"># Preeclampsia screening example</span></span>
<span id="cb5-37"><a href=""></a><span class="fu">bayes_diagnostic</span>(</span>
<span id="cb5-38"><a href=""></a>  <span class="at">sensitivity =</span> <span class="fl">0.90</span>,</span>
<span id="cb5-39"><a href=""></a>  <span class="at">specificity =</span> <span class="fl">0.85</span>,</span>
<span id="cb5-40"><a href=""></a>  <span class="at">prevalence  =</span> <span class="fl">0.05</span></span>
<span id="cb5-41"><a href=""></a>)</span>
<span id="cb5-42"><a href=""></a></span>
<span id="cb5-43"><a href=""></a><span class="co"># What if prevalence is higher (e.g., high-risk population)?</span></span>
<span id="cb5-44"><a href=""></a><span class="fu">bayes_diagnostic</span>(</span>
<span id="cb5-45"><a href=""></a>  <span class="at">sensitivity =</span> <span class="fl">0.90</span>,</span>
<span id="cb5-46"><a href=""></a>  <span class="at">specificity =</span> <span class="fl">0.85</span>,</span>
<span id="cb5-47"><a href=""></a>  <span class="at">prevalence  =</span> <span class="fl">0.20</span></span>
<span id="cb5-48"><a href=""></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>Note how the PPV changes dramatically with prevalence:</strong> At 5% prevalence, PPV is ~24%. At 20% prevalence, PPV rises to ~60%. The same test, the same sensitivity and specificity – but the <em>meaning</em> of a positive result depends entirely on the <strong>base rate</strong>. This is why the Prosecutor’s Fallacy is so dangerous.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Key Takeaways</h2>
<div class="key-takeaway">
<p><strong>Simpson’s Paradox</strong> arises when a confounder creates a fork structure in the DAG. Aggregated data can reverse the true causal effect. Always stratify by confounders, never by mediators.</p>
<p><strong>The Prosecutor’s Fallacy</strong> confuses <span class="math inline">\(P(E \mid H)\)</span> with <span class="math inline">\(P(H \mid E)\)</span>. Base rates matter. Use Bayes’ rule to compute the correct posterior probability.</p>
<p><strong>In MNH cost-effectiveness</strong>, naive cross-country comparisons mislead because baseline severity and health system strength confound the treatment-outcome relationship. Causal adjustment can change which countries and interventions are prioritized – and save thousands of additional lives.</p>
</div>
</section>
<section class="slide level2">
<h2>Looking Ahead</h2>
<div class="callout-box">
<p><strong>Next: Chapter 7 – Decision Analysis and Value of Information</strong></p>
<p>We will build on the causal models from this chapter to make <strong>optimal decisions under uncertainty</strong>:</p>
<ul>
<li><strong>Decision trees</strong> for intervention selection under multiple scenarios</li>
<li><strong>Expected value of perfect information (EVPI):</strong> How much would it be worth to resolve our uncertainty before investing?</li>
<li><strong>Sensitivity analysis:</strong> Which uncertain parameters matter most for the allocation decision?</li>
<li><strong>Multi-criteria decision analysis:</strong> Balancing cost-effectiveness with equity, political feasibility, and sustainability</li>
</ul>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>The connection:</strong> Chapter 6 taught us how to <em>correctly estimate</em> causal effects (avoiding Simpson’s Paradox and the Prosecutor’s Fallacy). Chapter 7 teaches us how to use those estimates to <em>make optimal decisions</em> about where to invest the Beginnings Fund’s resources.</p>
</div>
</div>
</section>
<section class="slide level2" data-background-color="white">
<h2></h2>
<p><br><br><br></p>
<div style="text-align: center;">
<p><img data-src="bka-logo.png" width="250"></p>
<p><br></p>
<p><span style="color: #005CB9; font-size: 0.6em;">Inference and Intervention | Chapter 6: Modeling MNH Cost-Effectiveness</span></p>
<p><span style="color: #666; font-size: 0.5em;">BK Advisors</span></p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="bka-logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'slide',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>