<!DOCTYPE html>
<html lang="en"><head>
<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/tabby.min.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="BK Advisors">
  <meta name="dcterms.date" content="2026-03-07">
  <title>Chapter 8: Multi-Country Resource Allocation</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="index_files/libs/revealjs/dist/theme/quarto-6e9afe50719493a7abb77d07998557a4.css">
  <link href="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="index_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section data-background-color="#005CB9" class="quarto-title-block center">
  <h1 class="title">Chapter 8: Multi-Country Resource Allocation</h1>
  <p class="subtitle">Inference and Intervention | BK Advisors</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
BK Advisors 
</div>
</div>
</div>

  <p class="date">2026-03-07</p>
</section>
<section class="slide level2">
<h2>Learning Objectives</h2>
<p>After this chapter, you will be able to:</p>
<ul>
<li class="fragment">Frame a <strong>multi-country resource allocation</strong> problem as a puzzle with real tradeoffs</li>
<li class="fragment">Compare three intuitive allocation strategies: <strong>Concentrate, Spread, and Tiered</strong></li>
<li class="fragment">Explain why <strong>uncertainty</strong> makes the “obvious best answer” less obvious</li>
<li class="fragment">Use <strong>Monte Carlo simulation</strong> (“replaying the future 1,000 times”) to compare strategies</li>
<li class="fragment">Apply <strong>sequential decision making</strong> – “invest a little, watch, then decide”</li>
</ul>
</section>
<section class="slide level2">
<h2>Chapter Overview</h2>
<div class="step-flow">
<div class="step-item" style="border-left: 4px solid #005CB9;">
The Allocation<br>Puzzle
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #83BD00;">
Three<br>Strategies
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #F8A623;">
Uncertainty &amp;<br>Scenarios
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #FA7650;">
Replaying<br>the Future
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #3E9B6E;">
Sequential<br>Decisions
</div>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>The big idea:</strong> You have a fixed budget. Four countries need help. Each country is different – different problems, different strengths, different risks. How do you split the money? There is no formula that spits out the “right” answer, but there <em>are</em> smart ways to think about the tradeoffs.</p>
</div>
</div>
</section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>The Allocation Puzzle</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Four countries, limited budget, different needs</span></p>
</section>
<section class="slide level2">
<h2>The Question</h2>
<div class="definition-box">
<p><strong>The core puzzle:</strong> Imagine you lead a maternal and neonatal health (MNH) program with a fixed annual budget. Four East African countries need support. Each country has a different health burden, a different health system, and a different set of risks. How do you divide the budget?</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>What makes this hard:</strong></p>
<ul>
<li>Sending everything to one country might save the most lives – <em>if things go well</em></li>
<li>Spreading money equally feels fair, but might waste resources in places that cannot absorb them</li>
<li>You do not know the future: governments change, crises happen, programs surprise you</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box orange">
<p><strong>What this is NOT:</strong></p>
<ul>
<li>Not a math optimization problem with one “correct” answer</li>
<li>Not about picking a winner and ignoring everyone else</li>
<li>Not about guessing the future perfectly</li>
</ul>
<p>It is about making a <strong>smart bet</strong> when you do not have all the information.</p>
</div>
</div>
</div>
</div>
</section>
<section class="slide level2">
<h2>Why Not Just Give It All to the Country With the Biggest Problem?</h2>
<div class="callout-box">
<p>Intuition says: “Find the country with the worst maternal mortality, and send all the money there.” Sounds logical, right?</p>
</div>
<div class="fragment">
<p>But here is why that can backfire:</p>
<ul>
<li class="fragment"><strong>Absorption capacity.</strong> A country with weak infrastructure may not be able to spend the money effectively. More funding does not automatically mean more impact.</li>
<li class="fragment"><strong>Diminishing returns.</strong> The first million dollars does more than the tenth. After a certain point, each additional dollar saves fewer additional lives.</li>
<li class="fragment"><strong>Concentration risk.</strong> If you put all your eggs in one basket and something goes wrong (political crisis, leadership change, supply chain failure), you lose <em>everything</em>.</li>
<li class="fragment"><strong>Fairness and politics.</strong> Completely ignoring other countries creates tension with governments, donors, and partner organizations.</li>
</ul>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>The takeaway:</strong> The “best” allocation is not simply “all to the highest burden.” It is a balance of impact, risk, capacity, and strategic judgment. That is what makes this a puzzle.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Country Profiles</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">What the public data tells us about each country</span></p>
</section>
<section class="slide level2">
<h2>Four Countries, Four Profiles</h2>
<p>All data below comes from <strong>publicly available sources</strong> (WHO, World Bank, DHS surveys). These are real numbers for real countries.</p>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Indicator</th>
<th>Ethiopia</th>
<th>Rwanda</th>
<th>Kenya</th>
<th>Tanzania</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Maternal Mortality Ratio</strong> (per 100k live births)</td>
<td>267</td>
<td>248</td>
<td>342</td>
<td>238</td>
</tr>
<tr class="even">
<td><strong>Neonatal Mortality Rate</strong> (per 1,000 live births)</td>
<td>28</td>
<td>16</td>
<td>21</td>
<td>20</td>
</tr>
<tr class="odd">
<td><strong>Annual live births</strong> (approx.)</td>
<td>3.4 million</td>
<td>370,000</td>
<td>1.5 million</td>
<td>2.1 million</td>
</tr>
<tr class="even">
<td><strong>Health system</strong></td>
<td>8+ diverse regions</td>
<td>Strong centralized</td>
<td>Devolved (47 counties)</td>
<td>Workforce gap</td>
</tr>
<tr class="odd">
<td><strong>Key challenge</strong></td>
<td>Scale across vast geography</td>
<td>Sustaining gains</td>
<td>County-level variation</td>
<td>Rural staffing</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>Source:</strong> WHO Global Health Observatory; World Bank World Development Indicators; most recent Demographic and Health Surveys. Figures are approximate and may reflect different reporting years.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Reading the Profiles</h2>
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>Ethiopia</strong> has the highest NMR (28) and the largest birth cohort (3.4M). That means the <em>absolute number</em> of neonatal deaths is enormous. But Ethiopia also has 8+ regions with very different health systems – scaling programs is hard.</p>
</div>
<div class="callout-box green">
<p><strong>Rwanda</strong> has the lowest NMR (16) and a famously strong, centralized health system. Programs tend to work well here. But the birth cohort is small, so the absolute number of lives you can save is limited.</p>
</div>
</div>
<div class="col">
<div class="callout-box orange">
<p><strong>Kenya</strong> has the highest MMR (342) and a devolved system with 47 counties. Impact varies wildly depending on which county you work in. Some counties look like Rwanda; others look like Ethiopia.</p>
</div>
<div class="callout-box red">
<p><strong>Tanzania</strong> has a moderate burden (MMR 238, NMR 20) but a serious health workforce gap. There are not enough skilled birth attendants in rural areas. Without staff, equipment sits unused.</p>
</div>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>No single country dominates on every dimension.</strong> Ethiopia has the biggest need; Rwanda has the best system; Kenya has the highest maternal mortality; Tanzania has a critical workforce bottleneck. A smart allocation has to weigh all of these.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Three Strategies</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Concentrate, Spread, or Tiered?</span></p>
</section>
<section class="slide level2">
<h2>Strategy 1: Concentrate</h2>
<div class="definition-box">
<p><strong>Concentrate:</strong> Put the majority of the budget into one or two countries where you expect the highest absolute impact. In our case, that probably means Ethiopia (biggest birth cohort, highest NMR) and Kenya (highest MMR).</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box green">
<p><strong>Pros:</strong></p>
<ul>
<li>Maximizes <em>expected</em> lives saved if your top picks perform well</li>
<li>Simpler to manage – fewer countries means fewer coordination challenges</li>
<li>Deeper investment may push a country past a tipping point</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box red">
<p><strong>Cons:</strong></p>
<ul>
<li>If Ethiopia hits a political crisis or Kenya’s devolution slows rollout, you lose big</li>
<li>Rwanda and Tanzania are left with scraps – and their governments notice</li>
<li>You are making a big bet on a few uncertain outcomes</li>
</ul>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="example-block">
<p><span class="example-label">Illustrative Split</span></p>
<p>Ethiopia 50% | Kenya 30% | Tanzania 12% | Rwanda 8%</p>
<p><em>This is a hypothetical example for teaching purposes, not an actual program allocation.</em></p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Strategy 2: Spread</h2>
<div class="definition-box">
<p><strong>Spread:</strong> Divide the budget roughly equally across all four countries. Everyone gets a fair share.</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box green">
<p><strong>Pros:</strong></p>
<ul>
<li>Reduces risk – if one country struggles, the others can still deliver</li>
<li>Politically easier – no country feels ignored</li>
<li>You learn about all four countries simultaneously</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box red">
<p><strong>Cons:</strong></p>
<ul>
<li>You may spread too thin – none of the countries gets enough to make a real difference</li>
<li>Equal shares ignore the fact that Ethiopia has 9x the births of Rwanda</li>
<li>The best-performing country is underfunded; the weakest is overfunded</li>
</ul>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="example-block">
<p><span class="example-label">Illustrative Split</span></p>
<p>Ethiopia 25% | Kenya 25% | Tanzania 25% | Rwanda 25%</p>
<p><em>Equal allocation regardless of burden or capacity.</em></p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Strategy 3: Tiered</h2>
<div class="definition-box">
<p><strong>Tiered:</strong> Weight the allocation by a combination of health burden and system capacity. Countries with higher burden <em>and</em> reasonable capacity get more. Countries with low burden or weak capacity get less (but not zero).</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box green">
<p><strong>Pros:</strong></p>
<ul>
<li>Balances impact and risk – bigger countries get more, but not everything</li>
<li>Accounts for capacity – money goes where it can actually be used</li>
<li>Provides a rationale that is defensible to donors and governments</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box orange">
<p><strong>Cons:</strong></p>
<ul>
<li>Requires judgment calls about how to weight burden vs.&nbsp;capacity</li>
<li>More complex to explain and manage</li>
<li>“Weighted” does not mean “optimal” – the weights are still subjective</li>
</ul>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="example-block">
<p><span class="example-label">Illustrative Split</span></p>
<p>Ethiopia 40% | Kenya 28% | Tanzania 20% | Rwanda 12%</p>
<p><em>Weighted by burden (NMR x births) adjusted for system capacity.</em></p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Comparing the Three Strategies</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Feature</th>
<th>Concentrate</th>
<th>Spread</th>
<th>Tiered</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Expected impact</strong> (if things go well)</td>
<td>Highest</td>
<td>Lowest</td>
<td>Middle</td>
</tr>
<tr class="even">
<td><strong>Worst-case outcome</strong> (if things go badly)</td>
<td>Worst</td>
<td>Best</td>
<td>Middle</td>
</tr>
<tr class="odd">
<td><strong>Fairness / political acceptability</strong></td>
<td>Low</td>
<td>High</td>
<td>Medium</td>
</tr>
<tr class="even">
<td><strong>Management complexity</strong></td>
<td>Low</td>
<td>Medium</td>
<td>Medium</td>
</tr>
<tr class="odd">
<td><strong>Flexibility to adjust later</strong></td>
<td>Low (committed)</td>
<td>Medium</td>
<td>High</td>
</tr>
</tbody>
</table>
<div class="fragment">
<div class="callout-box">
<p><strong>Notice the pattern:</strong> There is a tradeoff between <em>expected impact</em> and <em>protection against bad outcomes</em>. The Concentrate strategy is like buying a single lottery ticket – high potential payoff, but risky. The Spread strategy is like buying insurance – less upside, but more protection. The Tiered strategy tries to get the best of both worlds.</p>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>No strategy is universally “best.”</strong> The right choice depends on how much risk you are willing to take, how uncertain the future is, and what your stakeholders value. The rest of this chapter gives you tools to think through that choice.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Uncertainty</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">We do not know exactly what will happen</span></p>
</section>
<section class="slide level2">
<h2>What Could Go Right – and What Could Go Wrong</h2>
<div class="callout-box">
<p><strong>The honest truth:</strong> No matter how good your analysis, the future is uncertain. Programs can exceed expectations or fall flat. The question is not “What <em>will</em> happen?” but <strong>“What <em>could</em> happen, and how likely is each scenario?”</strong></p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box green">
<p><strong>Things go well:</strong></p>
<ul>
<li>Government commits to sustaining the program</li>
<li>Health workers stay at their posts</li>
<li>Supply chains deliver on time</li>
<li>Community uptake is strong</li>
<li>Other donors add funding</li>
</ul>
<p><em>Probability: roughly 30-40% in most countries</em></p>
</div>
</div>
<div class="col">
<div class="callout-box red">
<p><strong>Things go poorly:</strong></p>
<ul>
<li>Political transition disrupts priorities</li>
<li>Trained workers leave for private sector</li>
<li>Drug stockouts undermine quality</li>
<li>Community resistance slows adoption</li>
<li>Other donors pull out</li>
</ul>
<p><em>Probability: roughly 10-20% in most countries</em></p>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>The middle ground (40-50% probability):</strong> Things go <em>okay</em>. Not everything works, but programs make meaningful progress. Some regions outperform; others underperform. This is the most likely scenario – and the hardest to plan for.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Scenarios for Each Country</h2>
<p>Let us assign rough probabilities to three scenarios for each country. These are illustrative, based on the public data and general knowledge of each country’s health system.</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Country</th>
<th>P(Things go well)</th>
<th>P(Middle ground)</th>
<th>P(Things go poorly)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Ethiopia</strong></td>
<td>0.30</td>
<td>0.50</td>
<td>0.20</td>
</tr>
<tr class="even">
<td><strong>Rwanda</strong></td>
<td>0.55</td>
<td>0.35</td>
<td>0.10</td>
</tr>
<tr class="odd">
<td><strong>Kenya</strong></td>
<td>0.35</td>
<td>0.45</td>
<td>0.20</td>
</tr>
<tr class="even">
<td><strong>Tanzania</strong></td>
<td>0.30</td>
<td>0.50</td>
<td>0.20</td>
</tr>
</tbody>
</table>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>Key pattern:</strong> Rwanda has the highest probability of “things go well” (strong system, political stability, track record). Ethiopia and Tanzania carry more downside risk. Kenya is in between – some counties are excellent, others are fragile.</p>
</div>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>These probabilities are judgment calls, not precise measurements.</strong> That is okay. The point of the exercise is not to nail the exact numbers – it is to force yourself to think about <em>how confident</em> you are in each country’s trajectory. Even approximate probabilities are better than ignoring uncertainty entirely.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Why Uncertainty Changes the Answer</h2>
<div class="example-block">
<p><span class="example-label">A Simple Illustration</span></p>
<p>Suppose you have 100 units of budget to split between two countries:</p>
<ul>
<li><strong>Country X:</strong> If things go well (50%), you save 200 lives. If things go poorly (50%), you save 20 lives. Expected value: 110 lives.</li>
<li><strong>Country Y:</strong> If things go well (50%), you save 130 lives. If things go poorly (50%), you save 90 lives. Expected value: 110 lives.</li>
</ul>
<p>Same expected value! But very different risk profiles.</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>If you put everything in Country X:</strong></p>
<ul>
<li>Best case: 200 lives</li>
<li>Worst case: 20 lives</li>
<li>You are gambling</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box green">
<p><strong>If you split 50/50:</strong></p>
<ul>
<li>Best case: 165 lives (lower)</li>
<li>Worst case: 55 lives (much higher)</li>
<li>You are diversifying</li>
</ul>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>Diversification reduces your worst-case outcome.</strong> This is the same logic behind not putting all your savings in one stock. In global health, the “worst case” is measured in lives lost – which makes diversification especially important.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>Replaying the Future</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Monte Carlo simulation – imagining 1,000 possible futures</span></p>
</section>
<section class="slide level2">
<h2>What Is Monte Carlo Simulation?</h2>
<div class="definition-box">
<p><strong>Monte Carlo simulation</strong> is a way of exploring uncertainty by letting a computer “replay the future” thousands of times. Each replay randomly picks a scenario for each country (things go well, middle ground, things go poorly), calculates the outcome, and records it. After 1,000 replays, you have a picture of <em>all the things that could happen</em> – not just the average.</p>
</div>
<div class="fragment">
<p>Think of it like this:</p>
<ul>
<li class="fragment">You write each scenario on a slip of paper and put them in a hat</li>
<li class="fragment">You draw a slip for Ethiopia, a slip for Rwanda, a slip for Kenya, a slip for Tanzania</li>
<li class="fragment">You calculate the total lives saved under that combination of draws</li>
<li class="fragment">You put the slips back, shake the hat, and draw again</li>
<li class="fragment">After 1,000 rounds, you have 1,000 possible outcomes</li>
</ul>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>Why “Monte Carlo”?</strong> The technique is named after the Monte Carlo casino in Monaco – because it uses randomness (like rolling dice) to explore possibilities. It was developed by physicists working on the atomic bomb and is now used in everything from weather forecasting to financial planning to global health.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>What Monte Carlo Tells You</h2>
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>Without Monte Carlo:</strong></p>
<p>“Our best estimate is 5,000 lives saved.”</p>
<p>One number. No sense of uncertainty. Is this almost guaranteed? Or is it a coin flip?</p>
</div>
</div>
<div class="col">
<div class="callout-box green">
<p><strong>With Monte Carlo:</strong></p>
<p>“In 1,000 simulations, we saved between 2,100 and 8,400 lives. The middle 50% of outcomes fell between 4,200 and 6,100. There is a 10% chance we save fewer than 3,000.”</p>
<p>Now you understand the <em>range</em> of possibilities and can plan accordingly.</p>
</div>
</div>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>The key insight:</strong> Monte Carlo does not tell you what <em>will</em> happen. It tells you what <em>could</em> happen, and how often. This lets you compare strategies not just on their average outcome, but on their <em>entire distribution</em> of outcomes – including the best case, the worst case, and everything in between.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Comparing Strategies With Monte Carlo</h2>
<p>Imagine we run 1,000 simulations for each of our three strategies. Here is what the results might look like:</p>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Metric</th>
<th>Concentrate</th>
<th>Spread</th>
<th>Tiered</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Average lives saved</strong></td>
<td>5,200</td>
<td>4,600</td>
<td>5,000</td>
</tr>
<tr class="even">
<td><strong>Best case</strong> (top 5%)</td>
<td>8,400</td>
<td>6,100</td>
<td>7,200</td>
</tr>
<tr class="odd">
<td><strong>Worst case</strong> (bottom 5%)</td>
<td>1,800</td>
<td>3,200</td>
<td>2,700</td>
</tr>
<tr class="even">
<td><strong>Chance of saving &lt; 3,000</strong></td>
<td>18%</td>
<td>4%</td>
<td>9%</td>
</tr>
</tbody>
</table>
<p><em>Illustrative numbers for teaching purposes. Actual outcomes depend on program design, country context, and budget scale.</em></p>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>Read the table carefully:</strong></p>
<ul>
<li><strong>Concentrate</strong> has the highest average (5,200) but also the worst worst-case (1,800) and an 18% chance of falling below 3,000 lives.</li>
<li><strong>Spread</strong> has the lowest average (4,600) but the best worst-case (3,200) and only a 4% chance of falling below 3,000.</li>
<li><strong>Tiered</strong> is in between on every dimension – a compromise.</li>
</ul>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>Which strategy is “best” depends on what you care about.</strong> If you want the highest <em>expected</em> outcome and are willing to risk a bad result, go with Concentrate. If you want to protect against disaster, go with Spread. If you want a balance, go with Tiered. Monte Carlo makes this tradeoff visible.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>You Don’t Have to Decide Everything Today</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Sequential decisions – invest a little, watch, then decide</span></p>
</section>
<section class="slide level2">
<h2>The Power of “Wait and See”</h2>
<div class="callout-box">
<p><strong>A common mistake in resource allocation:</strong> treating it as a one-shot decision. “Here is the budget. Divide it now. Done.” But in reality, most programs operate over multiple years. You can make a <em>preliminary</em> allocation, observe what happens, and then <em>adjust</em>.</p>
</div>
<div class="fragment">
<div class="step-flow">
<div class="step-item" style="border-left: 4px solid #005CB9;">
<strong>Year 1</strong><br>Pilot funding<br>(invest a little)
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #F8A623;">
<strong>Observe</strong><br>Early results<br>(watch)
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #83BD00;">
<strong>Year 2+</strong><br>Scale or shift<br>(then decide)
</div>
<div class="step-arrow">
→
</div>
<div class="step-item" style="border-left: 4px solid #3E9B6E;">
<strong>Outcome</strong><br>Lives saved<br>(over full program)
</div>
</div>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>This is sequential decision making.</strong> Instead of committing 100% of the budget upfront, you commit a smaller amount, gather information, and then make a better-informed decision about the rest. It is the difference between placing one giant bet and playing a series of smaller, smarter bets.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>An Example: Two-Stage Allocation</h2>
<div class="example-block">
<p><span class="example-label">Hypothetical Scenario</span></p>
<p>Suppose you have a budget of 100 units over two years. You are deciding how much to invest in Tanzania, where outcomes are uncertain because of the workforce gap.</p>
<p><strong>Option A: Commit everything now.</strong> Send 30 units to Tanzania in Year 1.</p>
<p><strong>Option B: Pilot first.</strong> Send 10 units to Tanzania in Year 1 as a pilot. Based on what you learn, decide whether to send 20 more in Year 2 – or redirect those 20 units to another country.</p>
</div>
<div class="fragment">
<table class="caption-top">
<thead>
<tr class="header">
<th>Scenario</th>
<th>P</th>
<th>Option A (all-in)</th>
<th>Option B (pilot first)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Workforce holds, program succeeds</td>
<td>0.40</td>
<td>450 lives</td>
<td>420 lives</td>
</tr>
<tr class="even">
<td>Mixed results</td>
<td>0.40</td>
<td>250 lives</td>
<td>270 lives</td>
</tr>
<tr class="odd">
<td>Workforce collapses</td>
<td>0.20</td>
<td>60 lives</td>
<td>180 lives</td>
</tr>
<tr class="even">
<td><strong>Expected value</strong></td>
<td></td>
<td><strong>278 lives</strong></td>
<td><strong>300 lives</strong></td>
</tr>
</tbody>
</table>
<p><em>Illustrative numbers. The pilot approach yields a higher expected value because you avoid wasting resources when things go badly.</em></p>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>Why is Option B better?</strong> Because in the “workforce collapses” scenario, you only lose 10 units instead of 30. The 20 units you held back can be redirected to a country where they will do more good. The pilot buys you <em>information</em> – and information has value.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>The Cost of Waiting</h2>
<div class="callout-box red">
<p><strong>But waiting is not free.</strong> Every month you delay scaling up a successful program, preventable deaths are occurring. The pilot period is not just “gathering data” – it is a period when lives are at stake.</p>
</div>
<div class="fragment">
<div class="columns-equal">
<div class="col">
<div class="callout-box green">
<p><strong>Value of waiting:</strong></p>
<ul>
<li>Better information leads to better allocation</li>
<li>Avoid wasting resources on failing programs</li>
<li>Reduce the chance of catastrophic misallocation</li>
<li>Build evidence base for donors and governments</li>
</ul>
</div>
</div>
<div class="col">
<div class="callout-box red">
<p><strong>Cost of delay:</strong></p>
<ul>
<li>Preventable deaths during the pilot period</li>
<li>Political momentum may dissipate</li>
<li>Staff recruited for pilot may leave</li>
<li>Other donors may fill the gap (or leave it)</li>
</ul>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="key-takeaway">
<p><strong>The decision is not “wait vs.&nbsp;act” but “how much to commit now vs.&nbsp;later.”</strong> A good sequential strategy commits enough to start saving lives immediately, while holding back enough to adjust course when you learn more. Getting this balance right is one of the hardest calls in global health.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>When Sequential Decisions Work Best</h2>
<p>Sequential allocation is most valuable when:</p>
<ul>
<li class="fragment"><strong>Uncertainty is high.</strong> You genuinely do not know what will happen (e.g., a new country, an untested intervention)</li>
<li class="fragment"><strong>Information arrives quickly.</strong> You can learn meaningful things in 6-12 months, not 5 years</li>
<li class="fragment"><strong>Funds are flexible.</strong> You can actually redirect money from one country to another (not always easy with donor rules)</li>
<li class="fragment"><strong>The cost of delay is manageable.</strong> The program is not in a crisis where every day counts</li>
</ul>
<div class="fragment">
<div class="callout-box">
<p><strong>When it does NOT work well:</strong></p>
<ul>
<li>If the window for action is closing fast (e.g., disease outbreak)</li>
<li>If donor contracts lock in allocations for multiple years</li>
<li>If political commitments require upfront certainty (“We promised Tanzania $X”)</li>
<li>If the pilot is too small to generate useful information</li>
</ul>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>MNH Application</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Applying the three strategies to our four countries</span></p>
</section>
<section class="slide level2">
<h2>Setting Up the Problem</h2>
<div class="callout-box">
<p><strong>Scenario:</strong> You lead an MNH program with a fixed annual budget (let us call it 100 units for simplicity). You must allocate across Ethiopia, Rwanda, Kenya, and Tanzania. Your goal: maximize lives saved while managing risk.</p>
</div>
<div class="fragment">
<p>Using the public data from our country profiles, we can estimate a rough “impact score” for each country:</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Country</th>
<th>NMR</th>
<th>Births (M)</th>
<th>Preventable deaths (est.)</th>
<th>System capacity</th>
<th>Impact score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Ethiopia</strong></td>
<td>28</td>
<td>3.4</td>
<td>~95,000</td>
<td>Medium</td>
<td>High burden, moderate capacity</td>
</tr>
<tr class="even">
<td><strong>Rwanda</strong></td>
<td>16</td>
<td>0.37</td>
<td>~6,000</td>
<td>Strong</td>
<td>Lower burden, high capacity</td>
</tr>
<tr class="odd">
<td><strong>Kenya</strong></td>
<td>21</td>
<td>1.5</td>
<td>~32,000</td>
<td>Variable</td>
<td>High burden, variable capacity</td>
</tr>
<tr class="even">
<td><strong>Tanzania</strong></td>
<td>20</td>
<td>2.1</td>
<td>~42,000</td>
<td>Weak-Medium</td>
<td>High burden, capacity gap</td>
</tr>
</tbody>
</table>
<p><em>Preventable deaths estimated as NMR x births x fraction preventable with known interventions. Approximate figures for illustration.</em></p>
</div>
</section>
<section class="slide level2">
<h2>The Three Strategies Applied</h2>
<div class="columns-equal">
<div class="col">
<div class="callout-box">
<p><strong>Concentrate</strong></p>
<p>Ethiopia 50% | Kenya 30% Tanzania 12% | Rwanda 8%</p>
<p><em>Logic:</em> Ethiopia and Kenya account for ~73% of estimated preventable deaths. Focus resources where the numbers are biggest.</p>
</div>
</div>
<div class="col">
<div class="callout-box green">
<p><strong>Spread</strong></p>
<p>Ethiopia 25% | Kenya 25% Tanzania 25% | Rwanda 25%</p>
<p><em>Logic:</em> Every country gets a fair share. Reduces risk from any single country failing.</p>
</div>
</div>
<div class="col">
<div class="callout-box orange">
<p><strong>Tiered</strong></p>
<p>Ethiopia 40% | Kenya 28% Tanzania 20% | Rwanda 12%</p>
<p><em>Logic:</em> Weight by burden adjusted for capacity. Ethiopia gets the most (high burden), but not everything. Rwanda gets least (low burden), but enough to maintain programs.</p>
</div>
</div>
</div>
</section>
<section class="slide level2">
<h2>Expected Outcomes Under Each Strategy</h2>
<p>Using our scenario probabilities and illustrative impact assumptions:</p>
<div class="fragment">
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Strategy</th>
<th>Expected lives saved</th>
<th>Best case (top 10%)</th>
<th>Worst case (bottom 10%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Concentrate</strong></td>
<td>~5,200</td>
<td>~8,400</td>
<td>~1,800</td>
</tr>
<tr class="even">
<td><strong>Spread</strong></td>
<td>~4,600</td>
<td>~6,100</td>
<td>~3,200</td>
</tr>
<tr class="odd">
<td><strong>Tiered</strong></td>
<td>~5,000</td>
<td>~7,200</td>
<td>~2,700</td>
</tr>
</tbody>
</table>
<p><em>Illustrative figures based on hypothetical budget and impact assumptions. Not actual program projections.</em></p>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>The Tiered strategy sacrifices about 4% of expected impact compared to Concentrate, but improves the worst-case outcome by 50%.</strong> That tradeoff – a small expected cost for a large reduction in downside risk – is why many real-world programs gravitate toward tiered allocations.</p>
</div>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>Which would you choose?</strong> There is no universally right answer. It depends on your risk tolerance, your donors’ expectations, and how much flexibility you have to adjust over time.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Adding Sequential Decisions</h2>
<div class="example-block">
<p><span class="example-label">A Tiered + Sequential Approach</span></p>
<p><strong>Year 1 (60% of budget):</strong></p>
<ul>
<li>Ethiopia 24% | Kenya 17% | Tanzania 12% | Rwanda 7%</li>
</ul>
<p><strong>Year 2 (40% of budget):</strong></p>
<ul>
<li>Reallocate based on Year 1 results</li>
<li>Countries performing well get scaled up</li>
<li>Countries struggling get reallocated to stronger performers</li>
</ul>
<p><strong>Expected outcome:</strong> ~5,100 lives (slightly higher than static Tiered, with much better worst-case protection)</p>
</div>
<div class="fragment">
<div class="callout-box orange">
<p><strong>The sequential version outperforms the static version</strong> because it allows you to redirect resources when you learn that a country is underperforming. The information you gain in Year 1 is valuable – and the Monte Carlo simulation in our R workshop will show you exactly how valuable.</p>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center" data-background-color="#005CB9">
<h1>R Workshop: Monte Carlo Strategy Comparison</h1>
<p><span style="color: rgba(255,255,255,0.7); font-size: 0.7em;">Replaying the future in R</span></p>
</section>
<section class="slide level2">
<h2>R Block 1: Setting Up the Countries</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb1-2"><a href=""></a></span>
<span id="cb1-3"><a href=""></a><span class="co"># Country profiles using PUBLIC data (WHO, World Bank)</span></span>
<span id="cb1-4"><a href=""></a>countries <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-5"><a href=""></a>  <span class="at">country =</span> <span class="fu">c</span>(<span class="st">"Ethiopia"</span>, <span class="st">"Rwanda"</span>, <span class="st">"Kenya"</span>, <span class="st">"Tanzania"</span>),</span>
<span id="cb1-6"><a href=""></a>  <span class="at">nmr =</span> <span class="fu">c</span>(<span class="dv">28</span>, <span class="dv">16</span>, <span class="dv">21</span>, <span class="dv">20</span>),           <span class="co"># neonatal mortality rate per 1,000</span></span>
<span id="cb1-7"><a href=""></a>  <span class="at">births_millions =</span> <span class="fu">c</span>(<span class="fl">3.4</span>, <span class="fl">0.37</span>, <span class="fl">1.5</span>, <span class="fl">2.1</span>),</span>
<span id="cb1-8"><a href=""></a>  <span class="at">p_good =</span> <span class="fu">c</span>(<span class="fl">0.30</span>, <span class="fl">0.55</span>, <span class="fl">0.35</span>, <span class="fl">0.30</span>),  <span class="co"># P(things go well)</span></span>
<span id="cb1-9"><a href=""></a>  <span class="at">p_mid  =</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.35</span>, <span class="fl">0.45</span>, <span class="fl">0.50</span>),  <span class="co"># P(middle ground)</span></span>
<span id="cb1-10"><a href=""></a>  <span class="at">p_bad  =</span> <span class="fu">c</span>(<span class="fl">0.20</span>, <span class="fl">0.10</span>, <span class="fl">0.20</span>, <span class="fl">0.20</span>)   <span class="co"># P(things go poorly)</span></span>
<span id="cb1-11"><a href=""></a>)</span>
<span id="cb1-12"><a href=""></a></span>
<span id="cb1-13"><a href=""></a><span class="co"># Estimated preventable neonatal deaths (in thousands)</span></span>
<span id="cb1-14"><a href=""></a><span class="co"># Rough estimate: NMR * births * fraction preventable (~0.5)</span></span>
<span id="cb1-15"><a href=""></a>countries<span class="sc">$</span>preventable_k <span class="ot">&lt;-</span> <span class="fu">with</span>(countries,</span>
<span id="cb1-16"><a href=""></a>  nmr <span class="sc">*</span> births_millions <span class="sc">*</span> <span class="fl">0.5</span></span>
<span id="cb1-17"><a href=""></a>)</span>
<span id="cb1-18"><a href=""></a></span>
<span id="cb1-19"><a href=""></a>countries</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 2: The Simulation Function</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a><span class="co"># Simulate total lives saved for a given allocation strategy</span></span>
<span id="cb2-2"><a href=""></a><span class="co"># allocation = vector of proportions summing to 1 (or 100)</span></span>
<span id="cb2-3"><a href=""></a><span class="co"># n_sims = number of Monte Carlo replays</span></span>
<span id="cb2-4"><a href=""></a></span>
<span id="cb2-5"><a href=""></a>simulate_strategy <span class="ot">&lt;-</span> <span class="cf">function</span>(allocation, countries, <span class="at">n_sims =</span> <span class="dv">1000</span>) {</span>
<span id="cb2-6"><a href=""></a>  <span class="co"># Normalize allocation to proportions</span></span>
<span id="cb2-7"><a href=""></a>  alloc <span class="ot">&lt;-</span> allocation <span class="sc">/</span> <span class="fu">sum</span>(allocation)</span>
<span id="cb2-8"><a href=""></a>  results <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_sims)</span>
<span id="cb2-9"><a href=""></a></span>
<span id="cb2-10"><a href=""></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_sims) {</span>
<span id="cb2-11"><a href=""></a>    total_lives <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb2-12"><a href=""></a></span>
<span id="cb2-13"><a href=""></a>    <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(countries)) {</span>
<span id="cb2-14"><a href=""></a>      <span class="co"># Draw a scenario for this country</span></span>
<span id="cb2-15"><a href=""></a>      scenario <span class="ot">&lt;-</span> <span class="fu">sample</span>(</span>
<span id="cb2-16"><a href=""></a>        <span class="fu">c</span>(<span class="st">"good"</span>, <span class="st">"mid"</span>, <span class="st">"bad"</span>), <span class="at">size =</span> <span class="dv">1</span>,</span>
<span id="cb2-17"><a href=""></a>        <span class="at">prob =</span> <span class="fu">c</span>(countries<span class="sc">$</span>p_good[j],</span>
<span id="cb2-18"><a href=""></a>                 countries<span class="sc">$</span>p_mid[j],</span>
<span id="cb2-19"><a href=""></a>                 countries<span class="sc">$</span>p_bad[j])</span>
<span id="cb2-20"><a href=""></a>      )</span>
<span id="cb2-21"><a href=""></a></span>
<span id="cb2-22"><a href=""></a>      <span class="co"># Effectiveness multiplier depends on scenario</span></span>
<span id="cb2-23"><a href=""></a>      multiplier <span class="ot">&lt;-</span> <span class="cf">switch</span>(scenario,</span>
<span id="cb2-24"><a href=""></a>        <span class="at">good =</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="fl">0.80</span>, <span class="fl">1.00</span>),  <span class="co"># 80-100% of potential</span></span>
<span id="cb2-25"><a href=""></a>        <span class="at">mid  =</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="fl">0.40</span>, <span class="fl">0.70</span>),  <span class="co"># 40-70% of potential</span></span>
<span id="cb2-26"><a href=""></a>        <span class="at">bad  =</span> <span class="fu">runif</span>(<span class="dv">1</span>, <span class="fl">0.05</span>, <span class="fl">0.25</span>)   <span class="co"># 5-25% of potential</span></span>
<span id="cb2-27"><a href=""></a>      )</span>
<span id="cb2-28"><a href=""></a></span>
<span id="cb2-29"><a href=""></a>      <span class="co"># Lives saved = allocation share * preventable deaths * multiplier</span></span>
<span id="cb2-30"><a href=""></a>      lives_j <span class="ot">&lt;-</span> alloc[j] <span class="sc">*</span> countries<span class="sc">$</span>preventable_k[j] <span class="sc">*</span> <span class="dv">1000</span> <span class="sc">*</span> multiplier</span>
<span id="cb2-31"><a href=""></a>      total_lives <span class="ot">&lt;-</span> total_lives <span class="sc">+</span> lives_j</span>
<span id="cb2-32"><a href=""></a>    }</span>
<span id="cb2-33"><a href=""></a>    results[i] <span class="ot">&lt;-</span> total_lives</span>
<span id="cb2-34"><a href=""></a>  }</span>
<span id="cb2-35"><a href=""></a>  <span class="fu">return</span>(results)</span>
<span id="cb2-36"><a href=""></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 3: Running the Three Strategies</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="co"># Define the three strategies (percentage allocations)</span></span>
<span id="cb3-2"><a href=""></a><span class="co">#                    ETH  RWA  KEN  TZA</span></span>
<span id="cb3-3"><a href=""></a>strat_concentrate <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">50</span>,   <span class="dv">8</span>,  <span class="dv">30</span>,  <span class="dv">12</span>)</span>
<span id="cb3-4"><a href=""></a>strat_spread      <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">25</span>,  <span class="dv">25</span>,  <span class="dv">25</span>,  <span class="dv">25</span>)</span>
<span id="cb3-5"><a href=""></a>strat_tiered      <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">40</span>,  <span class="dv">12</span>,  <span class="dv">28</span>,  <span class="dv">20</span>)</span>
<span id="cb3-6"><a href=""></a></span>
<span id="cb3-7"><a href=""></a><span class="co"># Run 1,000 simulations for each</span></span>
<span id="cb3-8"><a href=""></a>n_sims <span class="ot">&lt;-</span> <span class="dv">1000</span></span>
<span id="cb3-9"><a href=""></a></span>
<span id="cb3-10"><a href=""></a>sim_conc   <span class="ot">&lt;-</span> <span class="fu">simulate_strategy</span>(strat_concentrate, countries, n_sims)</span>
<span id="cb3-11"><a href=""></a>sim_spread <span class="ot">&lt;-</span> <span class="fu">simulate_strategy</span>(strat_spread, countries, n_sims)</span>
<span id="cb3-12"><a href=""></a>sim_tiered <span class="ot">&lt;-</span> <span class="fu">simulate_strategy</span>(strat_tiered, countries, n_sims)</span>
<span id="cb3-13"><a href=""></a></span>
<span id="cb3-14"><a href=""></a><span class="co"># Summary statistics</span></span>
<span id="cb3-15"><a href=""></a>summary_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb3-16"><a href=""></a>  <span class="at">Strategy =</span> <span class="fu">c</span>(<span class="st">"Concentrate"</span>, <span class="st">"Spread"</span>, <span class="st">"Tiered"</span>),</span>
<span id="cb3-17"><a href=""></a>  <span class="at">Mean =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">mean</span>(sim_conc), <span class="fu">mean</span>(sim_spread), <span class="fu">mean</span>(sim_tiered))),</span>
<span id="cb3-18"><a href=""></a>  <span class="at">Median =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">median</span>(sim_conc), <span class="fu">median</span>(sim_spread), <span class="fu">median</span>(sim_tiered))),</span>
<span id="cb3-19"><a href=""></a>  <span class="at">P5  =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">quantile</span>(sim_conc, <span class="fl">0.05</span>), <span class="fu">quantile</span>(sim_spread, <span class="fl">0.05</span>),</span>
<span id="cb3-20"><a href=""></a>                 <span class="fu">quantile</span>(sim_tiered, <span class="fl">0.05</span>))),</span>
<span id="cb3-21"><a href=""></a>  <span class="at">P95 =</span> <span class="fu">round</span>(<span class="fu">c</span>(<span class="fu">quantile</span>(sim_conc, <span class="fl">0.95</span>), <span class="fu">quantile</span>(sim_spread, <span class="fl">0.95</span>),</span>
<span id="cb3-22"><a href=""></a>                 <span class="fu">quantile</span>(sim_tiered, <span class="fl">0.95</span>)))</span>
<span id="cb3-23"><a href=""></a>)</span>
<span id="cb3-24"><a href=""></a>summary_table</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 4: Visualizing the Distributions</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href=""></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-2"><a href=""></a></span>
<span id="cb4-3"><a href=""></a><span class="co"># Combine simulation results into one data frame</span></span>
<span id="cb4-4"><a href=""></a>sim_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-5"><a href=""></a>  <span class="at">lives =</span> <span class="fu">c</span>(sim_conc, sim_spread, sim_tiered),</span>
<span id="cb4-6"><a href=""></a>  <span class="at">strategy =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Concentrate"</span>, <span class="st">"Spread"</span>, <span class="st">"Tiered"</span>),</span>
<span id="cb4-7"><a href=""></a>                 <span class="at">each =</span> n_sims)</span>
<span id="cb4-8"><a href=""></a>)</span>
<span id="cb4-9"><a href=""></a></span>
<span id="cb4-10"><a href=""></a><span class="co"># Density plot: shows the full distribution for each strategy</span></span>
<span id="cb4-11"><a href=""></a><span class="fu">ggplot</span>(sim_df, <span class="fu">aes</span>(<span class="at">x =</span> lives <span class="sc">/</span> <span class="dv">1000</span>, <span class="at">fill =</span> strategy)) <span class="sc">+</span></span>
<span id="cb4-12"><a href=""></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb4-13"><a href=""></a>  <span class="fu">geom_vline</span>(</span>
<span id="cb4-14"><a href=""></a>    <span class="at">data =</span> <span class="fu">data.frame</span>(</span>
<span id="cb4-15"><a href=""></a>      <span class="at">strategy =</span> <span class="fu">c</span>(<span class="st">"Concentrate"</span>, <span class="st">"Spread"</span>, <span class="st">"Tiered"</span>),</span>
<span id="cb4-16"><a href=""></a>      <span class="at">mean_val =</span> <span class="fu">c</span>(<span class="fu">mean</span>(sim_conc), <span class="fu">mean</span>(sim_spread),</span>
<span id="cb4-17"><a href=""></a>                   <span class="fu">mean</span>(sim_tiered)) <span class="sc">/</span> <span class="dv">1000</span></span>
<span id="cb4-18"><a href=""></a>    ),</span>
<span id="cb4-19"><a href=""></a>    <span class="fu">aes</span>(<span class="at">xintercept =</span> mean_val, <span class="at">color =</span> strategy),</span>
<span id="cb4-20"><a href=""></a>    <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span></span>
<span id="cb4-21"><a href=""></a>  ) <span class="sc">+</span></span>
<span id="cb4-22"><a href=""></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#005CB9"</span>, <span class="st">"#83BD00"</span>, <span class="st">"#FA7650"</span>)) <span class="sc">+</span></span>
<span id="cb4-23"><a href=""></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#005CB9"</span>, <span class="st">"#83BD00"</span>, <span class="st">"#FA7650"</span>)) <span class="sc">+</span></span>
<span id="cb4-24"><a href=""></a>  <span class="fu">labs</span>(</span>
<span id="cb4-25"><a href=""></a>    <span class="at">x =</span> <span class="st">"Lives Saved (thousands)"</span>,</span>
<span id="cb4-26"><a href=""></a>    <span class="at">y =</span> <span class="st">"Density"</span>,</span>
<span id="cb4-27"><a href=""></a>    <span class="at">title =</span> <span class="st">"1,000 Simulated Futures: Three Allocation Strategies"</span>,</span>
<span id="cb4-28"><a href=""></a>    <span class="at">subtitle =</span> <span class="st">"Dashed lines = mean outcome for each strategy"</span></span>
<span id="cb4-29"><a href=""></a>  ) <span class="sc">+</span></span>
<span id="cb4-30"><a href=""></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb4-31"><a href=""></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>R Block 5: Which Strategy “Wins” Most Often?</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a><span class="co"># For each simulation, which strategy saved the most lives?</span></span>
<span id="cb5-2"><a href=""></a>wins <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb5-3"><a href=""></a>  <span class="at">sim =</span> <span class="dv">1</span><span class="sc">:</span>n_sims,</span>
<span id="cb5-4"><a href=""></a>  <span class="at">best =</span> <span class="fu">apply</span>(<span class="fu">cbind</span>(sim_conc, sim_spread, sim_tiered), <span class="dv">1</span>,</span>
<span id="cb5-5"><a href=""></a>               <span class="cf">function</span>(x) <span class="fu">c</span>(<span class="st">"Concentrate"</span>, <span class="st">"Spread"</span>, <span class="st">"Tiered"</span>)[<span class="fu">which.max</span>(x)])</span>
<span id="cb5-6"><a href=""></a>)</span>
<span id="cb5-7"><a href=""></a></span>
<span id="cb5-8"><a href=""></a><span class="co"># How often does each strategy "win"?</span></span>
<span id="cb5-9"><a href=""></a><span class="fu">table</span>(wins<span class="sc">$</span>best)</span>
<span id="cb5-10"><a href=""></a></span>
<span id="cb5-11"><a href=""></a><span class="co"># But also: how often does each strategy fall below a threshold?</span></span>
<span id="cb5-12"><a href=""></a>threshold <span class="ot">&lt;-</span> <span class="dv">2000</span>  <span class="co"># lives</span></span>
<span id="cb5-13"><a href=""></a><span class="fu">cat</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">Probability of saving fewer than"</span>, threshold, <span class="st">"lives:</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-14"><a href=""></a><span class="fu">cat</span>(<span class="st">"  Concentrate:"</span>, <span class="fu">mean</span>(sim_conc <span class="sc">&lt;</span> threshold), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-15"><a href=""></a><span class="fu">cat</span>(<span class="st">"  Spread:     "</span>, <span class="fu">mean</span>(sim_spread <span class="sc">&lt;</span> threshold), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span>
<span id="cb5-16"><a href=""></a><span class="fu">cat</span>(<span class="st">"  Tiered:     "</span>, <span class="fu">mean</span>(sim_tiered <span class="sc">&lt;</span> threshold), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<div class="callout-box">
<p><strong>Two ways to evaluate a strategy:</strong></p>
<ol type="1">
<li><strong>How often does it win?</strong> (Concentrate may win most individual simulations)</li>
<li><strong>How often does it fail badly?</strong> (Concentrate also has the highest chance of catastrophic shortfall)</li>
</ol>
<p>Which question matters more depends on your values and your risk tolerance.</p>
</div>
</div>
</section>
<section class="slide level2">
<h2>Key Takeaways</h2>
<div class="key-takeaway">
<p><strong>Resource allocation is a puzzle, not an optimization problem.</strong> The “right” answer depends on your risk tolerance, your values, and how much you know about the future.</p>
</div>
<div class="fragment">
<ul>
<li class="fragment"><strong>Three strategies</strong> offer different tradeoffs: Concentrate (high risk, high reward), Spread (low risk, lower reward), Tiered (balanced)</li>
<li class="fragment"><strong>Uncertainty</strong> means the “obvious best” country is not always the best bet – diversification protects against bad surprises</li>
<li class="fragment"><strong>Monte Carlo simulation</strong> lets you “replay the future” and see the full range of possible outcomes, not just the average</li>
<li class="fragment"><strong>Sequential decisions</strong> (“invest a little, watch, then decide”) let you buy information before committing fully</li>
<li class="fragment"><strong>The cost of delay is real</strong> – waiting to decide means lives lost today – so the art is finding the right balance between acting now and learning first</li>
<li class="fragment"><strong>Portfolio thinking</strong> applies to global health just as it applies to finance: do not put all your eggs in one basket</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Looking Ahead</h2>
<div class="callout-box">
<p><strong>Next: Chapter 9 – Multi-Agent Decision Making</strong></p>
<p>So far, we have treated the allocation as <em>your</em> decision alone. But in reality, other actors are making decisions too:</p>
<ul>
<li><strong>Governments</strong> deciding whether to co-finance or redirect funds</li>
<li><strong>Other donors</strong> deciding whether to invest alongside you or pull out</li>
<li><strong>Health workers</strong> deciding whether to stay or leave</li>
</ul>
<p>Chapter 9 introduces <strong>game theory</strong> – a framework for thinking about what happens when multiple decision-makers interact, each with their own objectives.</p>
</div>
<div class="fragment">
<div class="callout-box green">
<p><strong>From Chapter 8 to Chapter 9:</strong> We solved the allocation problem as if we were the only player on the field. In Chapter 9, we recognize that governments and donors are playing their own games – and our strategy needs to account for theirs.</p>
</div>
</div>
</section>
<section class="slide level2" data-background-color="white">
<h2></h2>
<p><br><br><br></p>
<div style="text-align: center;">
<p><img data-src="bka-logo.png" width="250"></p>
<p><br></p>
<p><span style="color: #005CB9; font-size: 0.6em;">Inference and Intervention | Chapter 8: Multi-Country Resource Allocation</span></p>
<p><span style="color: #666; font-size: 0.5em;">BK Advisors</span></p>
</div>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="bka-logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="index_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="index_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="index_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="index_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="index_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="index_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="index_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="index_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'slide',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>